/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.DNSModuleProtocolType
import kotlin.String

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 */
@Serializable

@SerialName(value = "https")
data class DNSModuleProtocolTypehttps (

    @Contextual @SerialName(value = "url")
    val url: String

) : DNSModuleProtocolType() {


}

