/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import kotlin.String

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bypassDomains 
 * @param id 
 * @param pacURL 
 * @param proxy 
 * @param secureProxy 
 */
@Serializable

data class HTTPProxyModule (

    @SerialName(value = "bypassDomains")
    val bypassDomains: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "pacURL")
    val pacURL: String? = null,

    @SerialName(value = "proxy")
    val proxy: kotlin.String? = null,

    @SerialName(value = "secureProxy")
    val secureProxy: kotlin.String? = null

) {


}

