/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.IPSettings
import io.partout.abi.OpenVPNCipher
import io.partout.abi.OpenVPNCompressionAlgorithm
import io.partout.abi.OpenVPNCompressionFraming
import io.partout.abi.OpenVPNCryptoContainer
import io.partout.abi.OpenVPNDigest
import io.partout.abi.OpenVPNObfuscationMethod
import io.partout.abi.OpenVPNPullMask
import io.partout.abi.OpenVPNRoutingPolicy
import io.partout.abi.OpenVPNTLSWrap
import io.partout.abi.Route
import kotlin.String

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authToken 
 * @param authUserPass 
 * @param ca 
 * @param checksEKU 
 * @param checksSANHost 
 * @param cipher 
 * @param clientCertificate 
 * @param clientKey 
 * @param compressionAlgorithm 
 * @param compressionFraming 
 * @param dataCiphers 
 * @param digest 
 * @param dnsDomain 
 * @param dnsServers 
 * @param httpProxy 
 * @param httpsProxy 
 * @param ipv4 
 * @param ipv6 
 * @param keepAliveInterval 
 * @param keepAliveTimeout 
 * @param mtu 
 * @param noPullMask 
 * @param peerId 
 * @param proxyAutoConfigurationURL 
 * @param proxyBypassDomains 
 * @param randomizeEndpoint 
 * @param randomizeHostnames 
 * @param remotes 
 * @param renegotiatesAfter 
 * @param routeGateway4 
 * @param routeGateway6 
 * @param routes4 
 * @param routes6 
 * @param routingPolicies 
 * @param sanHost 
 * @param searchDomains 
 * @param staticChallenge 
 * @param tlsSecurityLevel 
 * @param tlsWrap 
 * @param usesPIAPatches 
 * @param xorMethod 
 */
@Serializable

data class OpenVPNConfiguration (

    @SerialName(value = "authToken")
    val authToken: kotlin.String? = null,

    @SerialName(value = "authUserPass")
    val authUserPass: kotlin.Boolean? = null,

    @SerialName(value = "ca")
    val ca: OpenVPNCryptoContainer? = null,

    @SerialName(value = "checksEKU")
    val checksEKU: kotlin.Boolean? = null,

    @SerialName(value = "checksSANHost")
    val checksSANHost: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "cipher")
    val cipher: OpenVPNCipher? = null,

    @SerialName(value = "clientCertificate")
    val clientCertificate: OpenVPNCryptoContainer? = null,

    @SerialName(value = "clientKey")
    val clientKey: OpenVPNCryptoContainer? = null,

    @Contextual @SerialName(value = "compressionAlgorithm")
    val compressionAlgorithm: OpenVPNCompressionAlgorithm? = null,

    @Contextual @SerialName(value = "compressionFraming")
    val compressionFraming: OpenVPNCompressionFraming? = null,

    @SerialName(value = "dataCiphers")
    val dataCiphers: kotlin.collections.List<@Contextual OpenVPNCipher>? = null,

    @Contextual @SerialName(value = "digest")
    val digest: OpenVPNDigest? = null,

    @SerialName(value = "dnsDomain")
    val dnsDomain: kotlin.String? = null,

    @SerialName(value = "dnsServers")
    val dnsServers: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "httpProxy")
    val httpProxy: kotlin.String? = null,

    @SerialName(value = "httpsProxy")
    val httpsProxy: kotlin.String? = null,

    @SerialName(value = "ipv4")
    val ipv4: IPSettings? = null,

    @SerialName(value = "ipv6")
    val ipv6: IPSettings? = null,

    @Contextual @SerialName(value = "keepAliveInterval")
    val keepAliveInterval: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "keepAliveTimeout")
    val keepAliveTimeout: java.math.BigDecimal? = null,

    @SerialName(value = "mtu")
    val mtu: kotlin.Int? = null,

    @SerialName(value = "noPullMask")
    val noPullMask: kotlin.collections.List<@Contextual OpenVPNPullMask>? = null,

    @SerialName(value = "peerId")
    val peerId: kotlin.Int? = null,

    @Contextual @SerialName(value = "proxyAutoConfigurationURL")
    val proxyAutoConfigurationURL: String? = null,

    @SerialName(value = "proxyBypassDomains")
    val proxyBypassDomains: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "randomizeEndpoint")
    val randomizeEndpoint: kotlin.Boolean? = null,

    @SerialName(value = "randomizeHostnames")
    val randomizeHostnames: kotlin.Boolean? = null,

    @SerialName(value = "remotes")
    val remotes: kotlin.collections.List<kotlin.String>? = null,

    @Contextual @SerialName(value = "renegotiatesAfter")
    val renegotiatesAfter: java.math.BigDecimal? = null,

    @SerialName(value = "routeGateway4")
    val routeGateway4: kotlin.String? = null,

    @SerialName(value = "routeGateway6")
    val routeGateway6: kotlin.String? = null,

    @SerialName(value = "routes4")
    val routes4: kotlin.collections.List<Route>? = null,

    @SerialName(value = "routes6")
    val routes6: kotlin.collections.List<Route>? = null,

    @SerialName(value = "routingPolicies")
    val routingPolicies: kotlin.collections.List<@Contextual OpenVPNRoutingPolicy>? = null,

    @SerialName(value = "sanHost")
    val sanHost: kotlin.String? = null,

    @SerialName(value = "searchDomains")
    val searchDomains: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "staticChallenge")
    val staticChallenge: kotlin.Boolean? = null,

    @SerialName(value = "tlsSecurityLevel")
    val tlsSecurityLevel: kotlin.Int? = null,

    @SerialName(value = "tlsWrap")
    val tlsWrap: OpenVPNTLSWrap? = null,

    @SerialName(value = "usesPIAPatches")
    val usesPIAPatches: kotlin.Boolean? = null,

    @SerialName(value = "xorMethod")
    val xorMethod: OpenVPNObfuscationMethod? = null

) {


}

