/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fileDescriptors 
 * @param originalModuleId 
 * @param requiresVirtualDevice 
 * @param address 
 * @param modules 
 */
@Serializable

data class TunnelRemoteInfo (

    @SerialName(value = "fileDescriptors")
    val fileDescriptors: kotlin.collections.List<kotlin.Int>,

    @SerialName(value = "originalModuleId")
    val originalModuleId: kotlin.String,

    @SerialName(value = "requiresVirtualDevice")
    val requiresVirtualDevice: kotlin.Boolean,

    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "modules")
    val modules: kotlin.collections.List<@Contextual kotlin.Any>? = null

) {


}

