/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param innerType 
 * @param json 
 */
@Serializable

data class CustomModule (

    @SerialName(value = "innerType")
    val innerType: kotlin.String,

    @Contextual @SerialName(value = "json")
    val json: kotlinx.serialization.json.JsonElement?

) {


}

