/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.DNSModuleProtocolType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hostname 
 */
@Serializable

@SerialName(value = "tls")
data class DNSModuleProtocolTypetls (

    @SerialName(value = "hostname")
    val hostname: kotlin.String

) : DNSModuleProtocolType() {


}

