/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.DNSModuleDomainPolicy
import io.partout.abi.DNSModuleProtocolType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param protocolType 
 * @param servers 
 * @param domainName 
 * @param domainPolicy 
 * @param inheritsVPN 
 * @param routesThroughVPN 
 * @param searchDomains 
 */
@Serializable

data class DNSModule (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "protocolType")
    val protocolType: DNSModuleProtocolType,

    @SerialName(value = "servers")
    val servers: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "domainName")
    val domainName: kotlin.String? = null,

    @Contextual @SerialName(value = "domainPolicy")
    val domainPolicy: DNSModuleDomainPolicy? = null,

    @SerialName(value = "inheritsVPN")
    val inheritsVPN: kotlin.Boolean? = null,

    @SerialName(value = "routesThroughVPN")
    val routesThroughVPN: kotlin.Boolean? = null,

    @SerialName(value = "searchDomains")
    val searchDomains: kotlin.collections.List<kotlin.String>? = null

) {


}

