/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.Route

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param excludedRoutes 
 * @param includedRoutes 
 * @param subnets 
 * @param legacySingleSubnet 
 */
@Serializable

data class IPSettings (

    @SerialName(value = "excludedRoutes")
    val excludedRoutes: kotlin.collections.List<Route>,

    @SerialName(value = "includedRoutes")
    val includedRoutes: kotlin.collections.List<Route>,

    @SerialName(value = "subnets")
    val subnets: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "legacySingleSubnet")
    val legacySingleSubnet: kotlin.String? = null

) {


}

