/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: udp,tcp,udp4,tcp4,udp6,tcp6
 */
@Serializable
enum class IPSocketType(val value: kotlin.String) {

    @SerialName(value = "UDP")
    udp("UDP"),

    @SerialName(value = "TCP")
    tcp("TCP"),

    @SerialName(value = "UDP4")
    udp4("UDP4"),

    @SerialName(value = "TCP4")
    tcp4("TCP4"),

    @SerialName(value = "UDP6")
    udp6("UDP6"),

    @SerialName(value = "TCP6")
    tcp6("TCP6");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is IPSocketType) "$data" else null

        /**
         * Returns a valid [IPSocketType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): IPSocketType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


