/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.OnDemandModuleOtherNetwork
import io.partout.abi.OnDemandModulePolicy

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param policy 
 * @param withOtherNetworks 
 * @param withSSIDs 
 */
@Serializable

data class OnDemandModule (

    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "policy")
    val policy: OnDemandModulePolicy,

    @SerialName(value = "withOtherNetworks")
    val withOtherNetworks: kotlin.collections.Set<@Contextual OnDemandModuleOtherNetwork>,

    @SerialName(value = "withSSIDs")
    val withSSIDs: kotlin.collections.Map<kotlin.String, kotlin.Boolean>

) {


}

