/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.OpenVPNStaticKey
import io.partout.abi.OpenVPNTLSWrapStrategy

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param key 
 * @param strategy 
 */
@Serializable

data class OpenVPNTLSWrap (

    @SerialName(value = "key")
    val key: OpenVPNStaticKey,

    @Contextual @SerialName(value = "strategy")
    val strategy: OpenVPNTLSWrapStrategy

) {


}

