/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.OpenVPNStaticKeyDirection

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `data` 
 * @param dir 
 */
@Serializable

data class OpenVPNStaticKey (

    @SerialName(value = "data")
    val `data`: kotlin.String,

    @Contextual @SerialName(value = "dir")
    val dir: OpenVPNStaticKeyDirection? = null

) {


}

