/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.OpenVPNCredentialsOTPMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param otpMethod 
 * @param password 
 * @param username 
 * @param otp 
 */
@Serializable

data class OpenVPNCredentials (

    @Contextual @SerialName(value = "otpMethod")
    val otpMethod: OpenVPNCredentialsOTPMethod,

    @SerialName(value = "password")
    val password: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "otp")
    val otp: kotlin.String? = null

) {


}

