/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: aes128cbc,aes192cbc,aes256cbc,aes128gcm,aes192gcm,aes256gcm
 */
@Serializable
enum class OpenVPNCipher(val value: kotlin.String) {

    @SerialName(value = "aes128cbc")
    aes128cbc("aes128cbc"),

    @SerialName(value = "aes192cbc")
    aes192cbc("aes192cbc"),

    @SerialName(value = "aes256cbc")
    aes256cbc("aes256cbc"),

    @SerialName(value = "aes128gcm")
    aes128gcm("aes128gcm"),

    @SerialName(value = "aes192gcm")
    aes192gcm("aes192gcm"),

    @SerialName(value = "aes256gcm")
    aes256gcm("aes256gcm");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OpenVPNCipher) "$data" else null

        /**
         * Returns a valid [OpenVPNCipher] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OpenVPNCipher? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


