/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.OpenVPNObfuscationMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param mask 
 */
@Serializable

@SerialName(value = "xormask")
data class OpenVPNObfuscationMethodxormask (

    @SerialName(value = "mask")
    val mask: kotlin.String

) : OpenVPNObfuscationMethod() {


}

