/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * 
 *
 * Values: disabled,compLZO,compress,compressV2
 */
@Serializable(with = OpenVPNCompressionFramingSerializer::class)
enum class OpenVPNCompressionFraming(val value: kotlin.Int) {

    disabled(0),

    compLZO(1),

    compress(2),

    compressV2(3);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OpenVPNCompressionFraming) "$data" else null

        /**
         * Returns a valid [OpenVPNCompressionFraming] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OpenVPNCompressionFraming? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object OpenVPNCompressionFramingSerializer : KSerializer<OpenVPNCompressionFraming> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): OpenVPNCompressionFraming {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return OpenVPNCompressionFraming.entries.firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: OpenVPNCompressionFraming) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


