/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: sha1,sha224,sha256,sha384,sha512
 */
@Serializable
enum class OpenVPNDigest(val value: kotlin.String) {

    @SerialName(value = "SHA1")
    sha1("SHA1"),

    @SerialName(value = "SHA224")
    sha224("SHA224"),

    @SerialName(value = "SHA256")
    sha256("SHA256"),

    @SerialName(value = "SHA384")
    sha384("SHA384"),

    @SerialName(value = "SHA512")
    sha512("SHA512");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OpenVPNDigest) "$data" else null

        /**
         * Returns a valid [OpenVPNDigest] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OpenVPNDigest? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


