/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: aes128cbc,aes192cbc,aes256cbc,aes128gcm,aes192gcm,aes256gcm
 */
@Serializable
enum class OpenVPNCipher(val value: kotlin.String) {

    @SerialName(value = "AES-128-CBC")
    aes128cbc("AES-128-CBC"),

    @SerialName(value = "AES-192-CBC")
    aes192cbc("AES-192-CBC"),

    @SerialName(value = "AES-256-CBC")
    aes256cbc("AES-256-CBC"),

    @SerialName(value = "AES-128-GCM")
    aes128gcm("AES-128-GCM"),

    @SerialName(value = "AES-192-GCM")
    aes192gcm("AES-192-GCM"),

    @SerialName(value = "AES-256-GCM")
    aes256gcm("AES-256-GCM");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OpenVPNCipher) "$data" else null

        /**
         * Returns a valid [OpenVPNCipher] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OpenVPNCipher? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


