/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param destination 
 * @param gateway 
 */
@Serializable

data class Route (

    @SerialName(value = "destination")
    val destination: kotlin.String? = null,

    @SerialName(value = "gateway")
    val gateway: kotlin.String? = null

) {


}

