/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.ProfileBehavior
import io.partout.abi.TaggedModule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param activeModulesIds 
 * @param id 
 * @param modules 
 * @param name 
 * @param behavior 
 * @param userInfo 
 * @param version 
 */
@Serializable

data class TaggedProfile (

    @SerialName(value = "activeModulesIds")
    val activeModulesIds: kotlin.collections.Set<kotlin.String>,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "modules")
    val modules: kotlin.collections.List<TaggedModule>,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "behavior")
    val behavior: ProfileBehavior? = null,

    @Contextual @SerialName(value = "userInfo")
    val userInfo: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "version")
    val version: kotlin.Int? = null

) {


}

