/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.WireGuardLocalInterface
import io.partout.abi.WireGuardRemoteInterface

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `interface` 
 * @param peers 
 */
@Serializable

data class WireGuardConfiguration (

    @SerialName(value = "interface")
    val `interface`: WireGuardLocalInterface,

    @SerialName(value = "peers")
    val peers: kotlin.collections.List<WireGuardRemoteInterface>

) {


}

