/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.WireGuardConfiguration

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param configuration 
 */
@Serializable

data class WireGuardModule (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "configuration")
    val configuration: WireGuardConfiguration? = null

) {


}

