/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param allowedIPs 
 * @param publicKey 
 * @param endpoint 
 * @param keepAlive 
 * @param preSharedKey 
 */
@Serializable

data class WireGuardRemoteInterface (

    @SerialName(value = "allowedIPs")
    val allowedIPs: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    @SerialName(value = "endpoint")
    val endpoint: kotlin.String? = null,

    @SerialName(value = "keepAlive")
    val keepAlive: kotlin.Int? = null,

    @SerialName(value = "preSharedKey")
    val preSharedKey: kotlin.String? = null

) {


}

