/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.DNSModule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param addresses 
 * @param privateKey 
 * @param dns 
 * @param mtu 
 */
@Serializable

data class WireGuardLocalInterface (

    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "privateKey")
    val privateKey: kotlin.String,

    @SerialName(value = "dns")
    val dns: DNSModule? = null,

    @SerialName(value = "mtu")
    val mtu: kotlin.Int? = null

) {


}

