//
// OpenAPIAppConstantsContainers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsContainers: Sendable, Codable, Hashable {

    public var local: String
    public var remote: String
    public var backup: String

    public init(local: String, remote: String, backup: String) {
        self.local = local
        self.remote = remote
        self.backup = backup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case local
        case remote
        case backup
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(local, forKey: .local)
        try container.encode(remote, forKey: .remote)
        try container.encode(backup, forKey: .backup)
    }
}

