//
// OpenAPICredits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPICredits: Sendable, Codable, Hashable {

    public var licenses: [OpenAPICreditsLicensesInner]
    public var notices: [OpenAPICreditsNoticesInner]
    public var translations: [String: [String]]

    public init(licenses: [OpenAPICreditsLicensesInner], notices: [OpenAPICreditsNoticesInner], translations: [String: [String]]) {
        self.licenses = licenses
        self.notices = notices
        self.translations = translations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case licenses
        case notices
        case translations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(licenses, forKey: .licenses)
        try container.encode(notices, forKey: .notices)
        try container.encode(translations, forKey: .translations)
    }
}

