//
// OpenAPIVersionRelease.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIVersionRelease: Sendable, Codable, Hashable {

    public var version: OpenAPISemanticVersion
    public var url: String

    public init(version: OpenAPISemanticVersion, url: String) {
        self.version = version
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(url, forKey: .url)
    }
}

