//
// OpenAPICreditsNoticesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPICreditsNoticesInner: Sendable, Codable, Hashable {

    public var name: String
    public var message: String

    public init(name: String, message: String) {
        self.name = name
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(message, forKey: .message)
    }
}

