//
// OpenAPIDistributionTarget.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIDistributionTarget: String, Sendable, Codable, CaseIterable {
    case appStore = "appStore"
    case developerID = "developerID"
    case enterprise = "enterprise"
}
