//
// OpenAPIAppConstantsEmails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsEmails: Sendable, Codable, Hashable {

    public var domain: String
    public var recipients: OpenAPIAppConstantsEmailsRecipients

    public init(domain: String, recipients: OpenAPIAppConstantsEmailsRecipients) {
        self.domain = domain
        self.recipients = recipients
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case recipients
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(domain, forKey: .domain)
        try container.encode(recipients, forKey: .recipients)
    }
}

