//
// OpenAPIConfigFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIConfigFlag: String, Sendable, Codable, CaseIterable {
    case appNotWorking = "appNotWorking"
    case daemonLooperV2 = "daemonLooperV2"
    case unknown = "unknown"
}
