//
// OpenAPIExperimentalPreferences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIExperimentalPreferences: Sendable, Codable, Hashable {

    public var ignoredConfigFlags: [OpenAPIConfigFlag]
    public var enabledConfigFlags: [OpenAPIConfigFlag]

    public init(ignoredConfigFlags: [OpenAPIConfigFlag], enabledConfigFlags: [OpenAPIConfigFlag]) {
        self.ignoredConfigFlags = ignoredConfigFlags
        self.enabledConfigFlags = enabledConfigFlags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ignoredConfigFlags
        case enabledConfigFlags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ignoredConfigFlags, forKey: .ignoredConfigFlags)
        try container.encode(enabledConfigFlags, forKey: .enabledConfigFlags)
    }
}

