//
// OpenAPIAppPreferences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppPreferences: Sendable, Codable, Hashable {

    public var configFlags: [OpenAPIConfigFlag]
    public var cryptoBackend: Int
    public var deviceId: String?
    public var dnsFallsBack: Bool
    public var experimental: OpenAPIExperimentalPreferences
    public var extensiveLogging: Bool
    /** 64-bit millis since UNIX epoch. */
    public var lastCheckedVersionTimestamp: Int64?
    public var lastCheckedVersion: String?
    public var lastUsedProfileUUID: String?
    public var logsPrivateData: Bool
    public var skipsPurchases: Bool

    public init(configFlags: [OpenAPIConfigFlag], cryptoBackend: Int, deviceId: String? = nil, dnsFallsBack: Bool, experimental: OpenAPIExperimentalPreferences, extensiveLogging: Bool, lastCheckedVersionTimestamp: Int64? = nil, lastCheckedVersion: String? = nil, lastUsedProfileUUID: String? = nil, logsPrivateData: Bool, skipsPurchases: Bool) {
        self.configFlags = configFlags
        self.cryptoBackend = cryptoBackend
        self.deviceId = deviceId
        self.dnsFallsBack = dnsFallsBack
        self.experimental = experimental
        self.extensiveLogging = extensiveLogging
        self.lastCheckedVersionTimestamp = lastCheckedVersionTimestamp
        self.lastCheckedVersion = lastCheckedVersion
        self.lastUsedProfileUUID = lastUsedProfileUUID
        self.logsPrivateData = logsPrivateData
        self.skipsPurchases = skipsPurchases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configFlags
        case cryptoBackend
        case deviceId
        case dnsFallsBack
        case experimental
        case extensiveLogging
        case lastCheckedVersionTimestamp
        case lastCheckedVersion
        case lastUsedProfileUUID
        case logsPrivateData
        case skipsPurchases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(configFlags, forKey: .configFlags)
        try container.encode(cryptoBackend, forKey: .cryptoBackend)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encode(dnsFallsBack, forKey: .dnsFallsBack)
        try container.encode(experimental, forKey: .experimental)
        try container.encode(extensiveLogging, forKey: .extensiveLogging)
        try container.encodeIfPresent(lastCheckedVersionTimestamp, forKey: .lastCheckedVersionTimestamp)
        try container.encodeIfPresent(lastCheckedVersion, forKey: .lastCheckedVersion)
        try container.encodeIfPresent(lastUsedProfileUUID, forKey: .lastUsedProfileUUID)
        try container.encode(logsPrivateData, forKey: .logsPrivateData)
        try container.encode(skipsPurchases, forKey: .skipsPurchases)
    }
}

