//
// OpenAPIConfigFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIConfigFlag: String, Sendable, Codable, CaseIterable {
    case appNotWorking = "appNotWorking"
    case unknown = "unknown"
    case zigOpenVPN = "zigOpenVPN"
    case zigRuntime = "zigRuntime"
    case zigWireGuard = "zigWireGuard"
}
