//
// OpenAPIAppFeature.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIAppFeature: String, Sendable, Codable, CaseIterable {
    case appleTV = "appleTV"
    case dns = "dns"
    case httpProxy = "httpProxy"
    case onDemand = "onDemand"
    case otp = "otp"
    case providers = "providers"
    case routing = "routing"
    case sharing = "sharing"
}
