//
// OpenAPIAppPreferenceKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIAppPreferenceKey: String, Sendable, Codable, CaseIterable {
    case configFlags = "configFlags"
    case cryptoBackend = "cryptoBackend"
    case deviceId = "deviceId"
    case dnsFallsBack = "dnsFallsBack"
    case experimental = "experimental"
    case extensiveLogging = "extensiveLogging"
    case lastCheckedVersion = "lastCheckedVersion"
    case lastCheckedVersionDate = "lastCheckedVersionDate"
    case lastUsedProfileId = "lastUsedProfileId"
    case logsPrivateData = "logsPrivateData"
    case skipsPurchases = "skipsPurchases"
}
