//
// OpenAPIProfileSharingFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIProfileSharingFlag: String, Sendable, Codable, CaseIterable {
    case shared = "shared"
    case tv = "tv"
}
