//
// OpenAPIVersionEventNew.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIVersionEventNew: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case versionEventNew = "VersionEventNew"
    }
    public let type: OpenAPIType = .versionEventNew
    public var release: OpenAPIVersionRelease

    public init(release: OpenAPIVersionRelease) {
        self.release = release
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case release
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(release, forKey: .release)
    }
}

