//
// OpenAPIIAPEventEligibleFeatures.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIIAPEventEligibleFeatures: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case iapeventeligiblefeatures = "IAPEventEligibleFeatures"
    }
    public let type: OpenAPIType = .iapeventeligiblefeatures
    public var features: [OpenAPIAppFeature]
    public var forComplete: Bool
    public var forFeedback: Bool

    public init(features: [OpenAPIAppFeature], forComplete: Bool, forFeedback: Bool) {
        self.features = features
        self.forComplete = forComplete
        self.forFeedback = forFeedback
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case features
        case forComplete
        case forFeedback
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(features, forKey: .features)
        try container.encode(forComplete, forKey: .forComplete)
        try container.encode(forFeedback, forKey: .forFeedback)
    }
}

