//
// OpenAPIWebReceiverEventNewUpload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIWebReceiverEventNewUpload: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case webReceiverEventNewUpload = "WebReceiverEventNewUpload"
    }
    public let type: OpenAPIType = .webReceiverEventNewUpload
    public var file: OpenAPIWebFileUpload

    public init(file: OpenAPIWebFileUpload) {
        self.file = file
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case file
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(file, forKey: .file)
    }
}

