//
// OpenAPIProfileEventDelete.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileEventDelete: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case profileEventDelete = "ProfileEventDelete"
    }
    public let type: OpenAPIType = .profileEventDelete
    public var ids: [String]

    public init(ids: [String]) {
        self.ids = ids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case ids
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(ids, forKey: .ids)
    }
}

