//
// OpenAPICreditsLicensesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPICreditsLicensesInner: Sendable, Codable, Hashable {

    public var name: String
    public var licenseName: String
    public var licenseURL: URL

    public init(name: String, licenseName: String, licenseURL: URL) {
        self.name = name
        self.licenseName = licenseName
        self.licenseURL = licenseURL
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case licenseName
        case licenseURL
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(licenseName, forKey: .licenseName)
        try container.encode(licenseURL, forKey: .licenseURL)
    }
}

