/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param distributionTarget 
 * @param displayName 
 * @param versionNumber 
 * @param buildNumber 
 * @param customUserLevel 
 * @param bundleStrings 
 */
@Serializable

data class AppBundle (

    @Contextual @SerialName(value = "distributionTarget")
    val distributionTarget: DistributionTarget,

    @SerialName(value = "displayName")
    val displayName: String,

    @SerialName(value = "versionNumber")
    val versionNumber: String,

    @SerialName(value = "buildNumber")
    val buildNumber: Int,

    @Contextual @SerialName(value = "customUserLevel")
    val customUserLevel: AppUserLevel? = null,

    @SerialName(value = "bundleStrings")
    val bundleStrings: Map<String, String>? = null

) {


}

