/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param bundle 
 * @param constants 
 */
@Serializable

data class AppConfiguration (

    @SerialName(value = "bundle")
    val bundle: AppBundle,

    @SerialName(value = "constants")
    val constants: AppConstants

) {


}

