/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param tag 
 * @param formatter 
 * @param sinceLast 
 * @param options 
 * @param filenames 
 */
@Serializable

data class AppConstantsLog (

    @SerialName(value = "tag")
    val tag: String,

    @SerialName(value = "formatter")
    val formatter: AppConstantsLogFormatter,

    @SerialName(value = "sinceLast")
    val sinceLast: Double,

    @SerialName(value = "options")
    val options: LocalLoggerOptions,

    @SerialName(value = "filenames")
    val filenames: AppConstantsLogFilenames? = null

) {


}

