/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param discussionsURL 
 * @param issuesURL 
 * @param rawURL 
 * @param latestReleaseURL 
 */
@Serializable

data class AppConstantsGithub (

    @SerialName(value = "discussionsURL")
    val discussionsURL: String,

    @SerialName(value = "issuesURL")
    val issuesURL: String,

    @SerialName(value = "rawURL")
    val rawURL: String,

    @SerialName(value = "latestReleaseURL")
    val latestReleaseURL: String

) {


}

