/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param profileTitleFormat 
 * @param refreshInterval 
 * @param dnsFallbackServers 
 * @param verification 
 * @param minDataCountDelta 
 */
@Serializable

data class AppConstantsTunnel (

    @SerialName(value = "profileTitleFormat")
    val profileTitleFormat: String,

    @SerialName(value = "refreshInterval")
    val refreshInterval: Double,

    @SerialName(value = "dnsFallbackServers")
    val dnsFallbackServers: List<String>,

    @SerialName(value = "verification")
    val verification: AppConstantsTunnelVerification,

    @SerialName(value = "minDataCountDelta")
    val minDataCountDelta: Long? = null

) {


}

