/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param homeURL 
 * @param eulaURL 
 * @param appStoreDownloadURL 
 * @param macDownloadURL 
 * @param configTTL 
 * @param betaTTLFactor 
 */
@Serializable

data class AppConstantsWebsites (

    @SerialName(value = "homeURL")
    val homeURL: String,

    @SerialName(value = "eulaURL")
    val eulaURL: String,

    @SerialName(value = "appStoreDownloadURL")
    val appStoreDownloadURL: String,

    @SerialName(value = "macDownloadURL")
    val macDownloadURL: String,

    @SerialName(value = "configTTL")
    val configTTL: Double,

    @SerialName(value = "betaTTLFactor")
    val betaTTLFactor: Double

) {


}

