/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param production 
 * @param beta 
 */
@Serializable

data class AppConstantsTunnelVerification (

    @SerialName(value = "production")
    val production: AppConstantsTunnelVerificationParameters,

    @SerialName(value = "beta")
    val beta: AppConstantsTunnelVerificationParameters

) {


}

