/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import io.partout.models.ModuleType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param moduleTypes 
 * @param secondaryModuleTypes 
 * @param fingerprint 
 * @param sharingFlags 
 * @param requiredFeatures 
 * @param primaryModuleType 
 * @param providerInfo 
 */
@Serializable

data class AppProfileHeader (

    @SerialName(value = "id")
    val id: String,

    @SerialName(value = "name")
    val name: String,

    @SerialName(value = "moduleTypes")
    val moduleTypes: List<@Contextual ModuleType>,

    @SerialName(value = "secondaryModuleTypes")
    val secondaryModuleTypes: List<@Contextual ModuleType>,

    @SerialName(value = "fingerprint")
    val fingerprint: String,

    @SerialName(value = "sharingFlags")
    val sharingFlags: List<@Contextual ProfileSharingFlag>,

    @SerialName(value = "requiredFeatures")
    val requiredFeatures: List<@Contextual AppFeature>,

    @Contextual @SerialName(value = "primaryModuleType")
    val primaryModuleType: ModuleType? = null,

    @SerialName(value = "providerInfo")
    val providerInfo: ProviderInfo? = null

) {


}

