/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param configFlags 
 * @param dnsFallsBack 
 * @param experimental 
 * @param extensiveLogging 
 * @param logsPrivateData 
 * @param newProfileEncoding 
 * @param relaxedVerification 
 * @param skipsPurchases 
 * @param deviceId 
 * @param lastCheckedVersionTimestamp 64-bit millis since UNIX epoch.
 * @param lastCheckedVersion 
 * @param lastUsedProfileUUID 
 */
@Serializable

data class AppPreferences (

    @SerialName(value = "configFlags")
    val configFlags: List<@Contextual ConfigFlag>,

    @SerialName(value = "dnsFallsBack")
    val dnsFallsBack: Boolean,

    @SerialName(value = "experimental")
    val experimental: ExperimentalPreferences,

    @SerialName(value = "extensiveLogging")
    val extensiveLogging: Boolean,

    @SerialName(value = "logsPrivateData")
    val logsPrivateData: Boolean,

    @SerialName(value = "newProfileEncoding")
    val newProfileEncoding: Boolean,

    @SerialName(value = "relaxedVerification")
    val relaxedVerification: Boolean,

    @SerialName(value = "skipsPurchases")
    val skipsPurchases: Boolean,

    @SerialName(value = "deviceId")
    val deviceId: String? = null,

    /* 64-bit millis since UNIX epoch. */
    @SerialName(value = "lastCheckedVersionTimestamp")
    val lastCheckedVersionTimestamp: Long? = null,

    @SerialName(value = "lastCheckedVersion")
    val lastCheckedVersion: String? = null,

    @SerialName(value = "lastUsedProfileUUID")
    val lastUsedProfileUUID: String? = null

) {


}

