/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param isEnabled 
 * @param status 
 * @param onDemand 
 * @param transfer 
 * @param lastErrorCode 
 */
@Serializable

data class AppTunnelInfo (

    @SerialName(value = "id")
    val id: String,

    @SerialName(value = "isEnabled")
    val isEnabled: Boolean,

    @Contextual @SerialName(value = "status")
    val status: AppProfileStatus,

    @SerialName(value = "onDemand")
    val onDemand: Boolean,

    @SerialName(value = "transfer")
    val transfer: ProfileTransfer? = null,

    @SerialName(value = "lastErrorCode")
    val lastErrorCode: String? = null

) {


}

