/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.json.JsonElement

/**
 * 
 *
 * @param rate 
 * @param minBuild 
 * @param `data` 
 */
@Serializable

data class ConfigBundleConfig (

    @SerialName(value = "rate")
    val rate: Int,

    @SerialName(value = "minBuild")
    val minBuild: Int? = null,

    @Contextual @SerialName(value = "data")
    val `data`: JsonElement? = null

) {


}

