/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param licenses 
 * @param notices 
 * @param translations 
 */
@Serializable

data class Credits (

    @SerialName(value = "licenses")
    val licenses: List<CreditsLicensesInner>,

    @SerialName(value = "notices")
    val notices: List<CreditsNoticesInner>,

    @SerialName(value = "translations")
    val translations: Map<String, List<String>>

) {


}

