/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param licenseName 
 * @param licenseURL 
 */
@Serializable

data class CreditsLicensesInner (

    @SerialName(value = "name")
    val name: String,

    @SerialName(value = "licenseName")
    val licenseName: String,

    @SerialName(value = "licenseURL")
    val licenseURL: String

) {


}

