/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: appStore,developerID,enterprise
 */
@Serializable
enum class DistributionTarget(val value: String) {

    @SerialName(value = "appStore")
    appStore("appStore"),

    @SerialName(value = "developerID")
    developerID("developerID"),

    @SerialName(value = "enterprise")
    enterprise("enterprise");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is DistributionTarget) "$data" else null

        /**
         * Returns a valid [DistributionTarget] for [data], null otherwise.
         */
        fun decode(data: Any?): DistributionTarget? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


