/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param isLoading 
 */
@Serializable

@SerialName(value = "IAPEventLoadReceipt")
data class IAPEventLoadReceipt (

    @SerialName(value = "isLoading")
    val isLoading: Boolean

) : Event() {


}

