/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param features 
 * @param forComplete 
 * @param forFeedback 
 */
@Serializable

@SerialName(value = "IAPEventEligibleFeatures")
data class IAPEventEligibleFeatures (

    @SerialName(value = "features")
    val features: List<@Contextual AppFeature>,

    @SerialName(value = "forComplete")
    val forComplete: Boolean,

    @SerialName(value = "forFeedback")
    val forFeedback: Boolean

) : Event() {


}

