/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param isEnabled 
 */
@Serializable

@SerialName(value = "IAPEventStatus")
data class IAPEventStatus (

    @SerialName(value = "isEnabled")
    val isEnabled: Boolean

) : Event() {


}

