/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import io.partout.models.TaggedProfile

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param profile 
 */
@Serializable

@SerialName(value = "MixedEventShouldReconnect")
data class MixedEventShouldReconnect (

    @Contextual @SerialName(value = "profile")
    val profile: TaggedProfile

) : Event() {


}

