/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param providerId 
 * @param countryCode 
 */
@Serializable

data class ProviderInfo (

    @SerialName(value = "providerId")
    val providerId: String,

    @SerialName(value = "countryCode")
    val countryCode: String? = null

) {


}

