/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param error 
 */
@Serializable

@SerialName(value = "WebReceiverEventUploadFailure")
data class WebReceiverEventUploadFailure (

    @SerialName(value = "error")
    val error: String

) : Event() {


}

