/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.business.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param website 
 */
@Serializable

@SerialName(value = "WebReceiverEventStart")
data class WebReceiverEventStart (

    @SerialName(value = "website")
    val website: WebsiteWithPasscode

) : Event() {


}

