/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi.models

import com.algoritmico.passepartout.abi.models.AppConstantsTunnelVerification

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param profileTitleFormat 
 * @param refreshInterval 
 * @param dnsFallbackServers 
 * @param verification 
 * @param minDataCountDelta 
 */
@Serializable

data class AppConstantsTunnel (

    @SerialName(value = "profileTitleFormat")
    val profileTitleFormat: kotlin.String,

    @SerialName(value = "refreshInterval")
    val refreshInterval: kotlin.Double,

    @SerialName(value = "dnsFallbackServers")
    val dnsFallbackServers: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "verification")
    val verification: AppConstantsTunnelVerification,

    @SerialName(value = "minDataCountDelta")
    val minDataCountDelta: kotlin.Long? = null

) {


}

