/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: corruptProviderModule,couldNotLaunch,emptyProducts,emptyProfileName,encoding,importError,incompatibleModules,incompleteModule,ineligibleProfile,interactiveLogin,invalidField,malformedModule,missingProviderEntity,moduleRequiresConnection,noActiveModules,notFound,openVPNPassphraseRequired,openVPNUnsupportedCompression,other,partout,permissionDenied,rateLimit,systemExtension,timeout,unexpectedResponse,urlRequestFailed,urlRequestUnavailable,verificationReceiptIsLoading,verificationRequiredFeatures,webReceiver,webUploader,wireGuardEmptyPeers
 */
@Serializable
enum class AppErrorCode(val value: kotlin.String) {

    @SerialName(value = "corruptProviderModule")
    corruptProviderModule("corruptProviderModule"),

    @SerialName(value = "couldNotLaunch")
    couldNotLaunch("couldNotLaunch"),

    @SerialName(value = "emptyProducts")
    emptyProducts("emptyProducts"),

    @SerialName(value = "emptyProfileName")
    emptyProfileName("emptyProfileName"),

    @SerialName(value = "encoding")
    encoding("encoding"),

    @SerialName(value = "importError")
    importError("importError"),

    @SerialName(value = "incompatibleModules")
    incompatibleModules("incompatibleModules"),

    @SerialName(value = "incompleteModule")
    incompleteModule("incompleteModule"),

    @SerialName(value = "ineligibleProfile")
    ineligibleProfile("ineligibleProfile"),

    @SerialName(value = "interactiveLogin")
    interactiveLogin("interactiveLogin"),

    @SerialName(value = "invalidField")
    invalidField("invalidField"),

    @SerialName(value = "malformedModule")
    malformedModule("malformedModule"),

    @SerialName(value = "missingProviderEntity")
    missingProviderEntity("missingProviderEntity"),

    @SerialName(value = "moduleRequiresConnection")
    moduleRequiresConnection("moduleRequiresConnection"),

    @SerialName(value = "noActiveModules")
    noActiveModules("noActiveModules"),

    @SerialName(value = "notFound")
    notFound("notFound"),

    @SerialName(value = "openVPNPassphraseRequired")
    openVPNPassphraseRequired("openVPNPassphraseRequired"),

    @SerialName(value = "openVPNUnsupportedCompression")
    openVPNUnsupportedCompression("openVPNUnsupportedCompression"),

    @SerialName(value = "other")
    other("other"),

    @SerialName(value = "partout")
    partout("partout"),

    @SerialName(value = "permissionDenied")
    permissionDenied("permissionDenied"),

    @SerialName(value = "rateLimit")
    rateLimit("rateLimit"),

    @SerialName(value = "systemExtension")
    systemExtension("systemExtension"),

    @SerialName(value = "timeout")
    timeout("timeout"),

    @SerialName(value = "unexpectedResponse")
    unexpectedResponse("unexpectedResponse"),

    @SerialName(value = "urlRequestFailed")
    urlRequestFailed("urlRequestFailed"),

    @SerialName(value = "urlRequestUnavailable")
    urlRequestUnavailable("urlRequestUnavailable"),

    @SerialName(value = "verificationReceiptIsLoading")
    verificationReceiptIsLoading("verificationReceiptIsLoading"),

    @SerialName(value = "verificationRequiredFeatures")
    verificationRequiredFeatures("verificationRequiredFeatures"),

    @SerialName(value = "webReceiver")
    webReceiver("webReceiver"),

    @SerialName(value = "webUploader")
    webUploader("webUploader"),

    @SerialName(value = "wireGuardEmptyPeers")
    wireGuardEmptyPeers("wireGuardEmptyPeers");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AppErrorCode) "$data" else null

        /**
         * Returns a valid [AppErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AppErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


