/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi.models

import com.algoritmico.passepartout.abi.models.AppPreferenceKey
import com.algoritmico.passepartout.abi.models.AppPreferencesPatchValues

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param propertyValues 
 * @param fieldsToUnset 
 */
@Serializable

data class AppPreferencesPatch (

    @SerialName(value = "values")
    val propertyValues: AppPreferencesPatchValues? = null,

    @SerialName(value = "fieldsToUnset")
    val fieldsToUnset: kotlin.collections.List<@Contextual AppPreferenceKey>? = null

) {


}

