/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: deviceId,configFlags,dnsFallsBack,dnsFallbackServers,experimental,extensiveLogging,lastCheckedVersionDate,lastCheckedVersion,lastUsedProfileId,logsPrivateData,newProfileEncoding,relaxedVerification,skipsPurchases
 */
@Serializable
enum class AppPreferenceKey(val value: kotlin.String) {

    @SerialName(value = "deviceId")
    deviceId("deviceId"),

    @SerialName(value = "configFlags")
    configFlags("configFlags"),

    @SerialName(value = "dnsFallsBack")
    dnsFallsBack("dnsFallsBack"),

    @SerialName(value = "dnsFallbackServers")
    dnsFallbackServers("dnsFallbackServers"),

    @SerialName(value = "experimental")
    experimental("experimental"),

    @SerialName(value = "extensiveLogging")
    extensiveLogging("extensiveLogging"),

    @SerialName(value = "lastCheckedVersionDate")
    lastCheckedVersionDate("lastCheckedVersionDate"),

    @SerialName(value = "lastCheckedVersion")
    lastCheckedVersion("lastCheckedVersion"),

    @SerialName(value = "lastUsedProfileId")
    lastUsedProfileId("lastUsedProfileId"),

    @SerialName(value = "logsPrivateData")
    logsPrivateData("logsPrivateData"),

    @SerialName(value = "newProfileEncoding")
    newProfileEncoding("newProfileEncoding"),

    @SerialName(value = "relaxedVerification")
    relaxedVerification("relaxedVerification"),

    @SerialName(value = "skipsPurchases")
    skipsPurchases("skipsPurchases");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AppPreferenceKey) "$data" else null

        /**
         * Returns a valid [AppPreferenceKey] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AppPreferenceKey? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


