/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi.models

import com.algoritmico.passepartout.abi.models.AppPreferencesPatch
import com.algoritmico.passepartout.abi.models.Event

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param patch 
 */
@Serializable

@SerialName(value = "MixedEventUpdatedPreferences")
data class MixedEventUpdatedPreferences (

    @SerialName(value = "patch")
    val patch: AppPreferencesPatch

) : Event() {


}

