/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi.models

import com.algoritmico.passepartout.abi.models.AppPreferenceKey
import com.algoritmico.passepartout.abi.models.AppPreferences
import com.algoritmico.passepartout.abi.models.Event

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param preferences 
 * @param fields 
 */
@Serializable

@SerialName(value = "MixedEventShouldUpdatePreferences")
data class MixedEventShouldUpdatePreferences (

    @SerialName(value = "preferences")
    val preferences: AppPreferences,

    @SerialName(value = "fields")
    val fields: kotlin.collections.List<@Contextual AppPreferenceKey>

) : Event() {


}

