included:
  - Passepartout/App
  - Passepartout/Intents
  - Passepartout/LoginItem
  - Passepartout/Shared
  - Passepartout/Tests
  - Passepartout/Tunnel
  - Passepartout/UITests
  - Packages/App/Sources
  - Packages/App/Tests
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - sorted_imports
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - generic_type_name
  - identifier_name
  - line_length
  - inclusive_language
  - nesting
  - todo
