/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param defaultDelay 
 * @param interval 
 * @param attempts 
 * @param retryInterval 
 * @param tvDelay 
 */
@Serializable

data class AppConstantsTunnelVerificationParameters (

    @SerialName(value = "defaultDelay")
    val defaultDelay: kotlin.Double,

    @SerialName(value = "interval")
    val interval: kotlin.Double,

    @SerialName(value = "attempts")
    val attempts: kotlin.Int,

    @SerialName(value = "retryInterval")
    val retryInterval: kotlin.Double,

    @SerialName(value = "tvDelay")
    val tvDelay: kotlin.Double? = null

) {


}

