/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param port 
 * @param passcodeLength 
 */
@Serializable

data class AppConstantsWebReceiver (

    @SerialName(value = "port")
    val port: kotlin.Int,

    @SerialName(value = "passcodeLength")
    val passcodeLength: kotlin.Int

) {


}

