/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param timeoutInterval 
 * @param versionRateLimit 
 * @param refreshInfrastructureRateLimit 
 */
@Serializable

data class AppConstantsApi (

    @SerialName(value = "timeoutInterval")
    val timeoutInterval: kotlin.Double,

    @SerialName(value = "versionRateLimit")
    val versionRateLimit: kotlin.Double,

    @SerialName(value = "refreshInfrastructureRateLimit")
    val refreshInfrastructureRateLimit: kotlin.Double

) {


}

