/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppConstantsLogFormatter
import com.algoritmico.passepartout.abi.LocalLoggerOptions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param formatter 
 * @param sinceLast 
 * @param options 
 */
@Serializable

data class AppConstantsLog (

    @SerialName(value = "formatter")
    val formatter: AppConstantsLogFormatter,

    @SerialName(value = "sinceLast")
    val sinceLast: kotlin.Double,

    @SerialName(value = "options")
    val options: LocalLoggerOptions

) {


}

