/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppConstantsEmailsRecipients

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param domain 
 * @param recipients 
 */
@Serializable

data class AppConstantsEmails (

    @SerialName(value = "domain")
    val domain: kotlin.String,

    @SerialName(value = "recipients")
    val recipients: AppConstantsEmailsRecipients

) {


}

