/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param issues 
 * @param beta 
 */
@Serializable

data class AppConstantsEmailsRecipients (

    @SerialName(value = "issues")
    val issues: kotlin.String,

    @SerialName(value = "beta")
    val beta: kotlin.String

) {


}

