/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param productsTimeoutInterval 
 * @param receiptInvalidationInterval 
 */
@Serializable

data class AppConstantsIap (

    @SerialName(value = "productsTimeoutInterval")
    val productsTimeoutInterval: kotlin.Double,

    @SerialName(value = "receiptInvalidationInterval")
    val receiptInvalidationInterval: kotlin.Double

) {


}

