/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppConstantsTunnelVerificationParameters

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param production 
 * @param beta 
 */
@Serializable

data class AppConstantsTunnelVerification (

    @SerialName(value = "production")
    val production: AppConstantsTunnelVerificationParameters,

    @SerialName(value = "beta")
    val beta: AppConstantsTunnelVerificationParameters

) {


}

