/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param local 
 * @param remote 
 * @param backup 
 */
@Serializable

data class AppConstantsContainers (

    @SerialName(value = "local")
    val local: kotlin.String,

    @SerialName(value = "remote")
    val remote: kotlin.String,

    @SerialName(value = "backup")
    val backup: kotlin.String

) {


}

