/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppConstantsApi
import com.algoritmico.passepartout.abi.AppConstantsContainers
import com.algoritmico.passepartout.abi.AppConstantsEmails
import com.algoritmico.passepartout.abi.AppConstantsFormats
import com.algoritmico.passepartout.abi.AppConstantsGithub
import com.algoritmico.passepartout.abi.AppConstantsIap
import com.algoritmico.passepartout.abi.AppConstantsLog
import com.algoritmico.passepartout.abi.AppConstantsTunnel
import com.algoritmico.passepartout.abi.AppConstantsWebReceiver
import com.algoritmico.passepartout.abi.AppConstantsWebsites

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param deviceIdLength 
 * @param containers 
 * @param websites 
 * @param github 
 * @param emails 
 * @param formats 
 * @param tunnel 
 * @param api 
 * @param iap 
 * @param webReceiver 
 * @param log 
 */
@Serializable

data class AppConstants (

    @SerialName(value = "deviceIdLength")
    val deviceIdLength: kotlin.Int,

    @SerialName(value = "containers")
    val containers: AppConstantsContainers,

    @SerialName(value = "websites")
    val websites: AppConstantsWebsites,

    @SerialName(value = "github")
    val github: AppConstantsGithub,

    @SerialName(value = "emails")
    val emails: AppConstantsEmails,

    @SerialName(value = "formats")
    val formats: AppConstantsFormats,

    @SerialName(value = "tunnel")
    val tunnel: AppConstantsTunnel,

    @SerialName(value = "api")
    val api: AppConstantsApi,

    @SerialName(value = "iap")
    val iap: AppConstantsIap,

    @SerialName(value = "webReceiver")
    val webReceiver: AppConstantsWebReceiver,

    @SerialName(value = "log")
    val log: AppConstantsLog

) {


}

