/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param homeURL 
 * @param eulaURL 
 * @param appStoreDownloadURL 
 * @param macDownloadURL 
 * @param configTTL 
 */
@Serializable

data class AppConstantsWebsites (

    @SerialName(value = "homeURL")
    val homeURL: kotlin.String,

    @SerialName(value = "eulaURL")
    val eulaURL: kotlin.String,

    @SerialName(value = "appStoreDownloadURL")
    val appStoreDownloadURL: kotlin.String,

    @SerialName(value = "macDownloadURL")
    val macDownloadURL: kotlin.String,

    @SerialName(value = "configTTL")
    val configTTL: kotlin.Double

) {


}

