/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: appleTV,dns,httpProxy,onDemand,otp,providers,routing,sharing
 */
@Serializable
enum class AppFeature(val value: kotlin.String) {

    @SerialName(value = "appleTV")
    appleTV("appleTV"),

    @SerialName(value = "dns")
    dns("dns"),

    @SerialName(value = "httpProxy")
    httpProxy("httpProxy"),

    @SerialName(value = "onDemand")
    onDemand("onDemand"),

    @SerialName(value = "otp")
    otp("otp"),

    @SerialName(value = "providers")
    providers("providers"),

    @SerialName(value = "routing")
    routing("routing"),

    @SerialName(value = "sharing")
    sharing("sharing");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AppFeature) "$data" else null

        /**
         * Returns a valid [AppFeature] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AppFeature? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


