/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppFeature
import com.algoritmico.passepartout.abi.ModuleType
import com.algoritmico.passepartout.abi.ProfileSharingFlag
import com.algoritmico.passepartout.abi.ProviderInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param moduleTypes 
 * @param secondaryModuleTypes 
 * @param fingerprint 
 * @param sharingFlags 
 * @param requiredFeatures 
 * @param primaryModuleType 
 * @param providerInfo 
 */
@Serializable

data class AppProfileHeader (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "moduleTypes")
    val moduleTypes: kotlin.collections.List<@Contextual ModuleType>,

    @SerialName(value = "secondaryModuleTypes")
    val secondaryModuleTypes: kotlin.collections.List<@Contextual ModuleType>,

    @SerialName(value = "fingerprint")
    val fingerprint: kotlin.String,

    @SerialName(value = "sharingFlags")
    val sharingFlags: kotlin.collections.List<@Contextual ProfileSharingFlag>,

    @SerialName(value = "requiredFeatures")
    val requiredFeatures: kotlin.collections.List<@Contextual AppFeature>,

    @Contextual @SerialName(value = "primaryModuleType")
    val primaryModuleType: ModuleType? = null,

    @SerialName(value = "providerInfo")
    val providerInfo: ProviderInfo? = null

) {


}

