/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppProfileStatus
import com.algoritmico.passepartout.abi.ProfileTransfer

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param rawId 
 * @param isEnabled 
 * @param status 
 * @param rawTunnelStatus 
 * @param onDemand 
 * @param transfer 
 * @param rawLastErrorCode 
 */
@Serializable

data class AppTunnelInfo (

    @SerialName(value = "rawId")
    val rawId: kotlin.String,

    @SerialName(value = "isEnabled")
    val isEnabled: kotlin.Boolean,

    @Contextual @SerialName(value = "status")
    val status: AppProfileStatus,

    @SerialName(value = "rawTunnelStatus")
    val rawTunnelStatus: kotlin.String,

    @SerialName(value = "onDemand")
    val onDemand: kotlin.Boolean,

    @SerialName(value = "transfer")
    val transfer: ProfileTransfer? = null,

    @SerialName(value = "rawLastErrorCode")
    val rawLastErrorCode: kotlin.String? = null

) {


}

