/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.ConfigFlag
import com.algoritmico.passepartout.abi.Event

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param flags 
 * @param `data` 
 */
@Serializable

@SerialName(value = "ConfigEventRefresh")
data class ConfigEventRefresh (

    @SerialName(value = "flags")
    val flags: kotlin.collections.List<@Contextual ConfigFlag>,

    @Contextual @SerialName(value = "data")
    val `data`: kotlin.Any

) : Event() {


}

