/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.CreditsLicensesInner
import com.algoritmico.passepartout.abi.CreditsNoticesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param licenses 
 * @param notices 
 * @param translations 
 */
@Serializable

data class Credits (

    @SerialName(value = "licenses")
    val licenses: kotlin.collections.List<CreditsLicensesInner>,

    @SerialName(value = "notices")
    val notices: kotlin.collections.List<CreditsNoticesInner>,

    @SerialName(value = "translations")
    val translations: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>

) {


}

