/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppFeature
import com.algoritmico.passepartout.abi.Event

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param features 
 * @param forComplete 
 * @param forFeedback 
 */
@Serializable

@SerialName(value = "IAPEventEligibleFeatures")
data class IAPEventEligibleFeatures (

    @SerialName(value = "features")
    val features: kotlin.collections.List<@Contextual AppFeature>,

    @SerialName(value = "forComplete")
    val forComplete: kotlin.Boolean,

    @SerialName(value = "forFeedback")
    val forFeedback: kotlin.Boolean

) : Event() {


}

