/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.LocalLoggerOptionsMaxLevel

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param maxLevel 
 * @param maxSize Maximum size in bytes
 * @param maxBufferedLines 
 * @param maxAge Optional maximum age in seconds
 */
@Serializable

data class LocalLoggerOptions (

    @Contextual @SerialName(value = "maxLevel")
    val maxLevel: LocalLoggerOptionsMaxLevel,

    /* Maximum size in bytes */
    @SerialName(value = "maxSize")
    val maxSize: kotlin.Int,

    @SerialName(value = "maxBufferedLines")
    val maxBufferedLines: kotlin.Int,

    /* Optional maximum age in seconds */
    @SerialName(value = "maxAge")
    val maxAge: kotlin.Double? = null

) {


}

