/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * DebugLog.Level (0=fault, 1=error, 2=notice, 3=info, 4=debug)
 *
 * Values: fault,error,notice,info,debug
 */
@Serializable(with = LocalLoggerOptionsMaxLevelSerializer::class)
enum class LocalLoggerOptionsMaxLevel(val value: kotlin.Int) {

    fault(0),

    error(1),

    notice(2),

    info(3),

    debug(4);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LocalLoggerOptionsMaxLevel) "$data" else null

        /**
         * Returns a valid [LocalLoggerOptionsMaxLevel] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LocalLoggerOptionsMaxLevel? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object LocalLoggerOptionsMaxLevelSerializer : KSerializer<LocalLoggerOptionsMaxLevel> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): LocalLoggerOptionsMaxLevel {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return LocalLoggerOptionsMaxLevel.entries.firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: LocalLoggerOptionsMaxLevel) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


