/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: DNS,HTTPProxy,IP,OnDemand,OpenVPN,WireGuard
 */
@Serializable
enum class ModuleType(val value: kotlin.String) {

    @SerialName(value = "DNS")
    DNS("DNS"),

    @SerialName(value = "HTTPProxy")
    HTTPProxy("HTTPProxy"),

    @SerialName(value = "IP")
    IP("IP"),

    @SerialName(value = "OnDemand")
    OnDemand("OnDemand"),

    @SerialName(value = "OpenVPN")
    OpenVPN("OpenVPN"),

    @SerialName(value = "WireGuard")
    WireGuard("WireGuard");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ModuleType) "$data" else null

        /**
         * Returns a valid [ModuleType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ModuleType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


