/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import io.partout.abi.ConnectionStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param profileId 
 * @param status 
 */
@Serializable

data class OnConnectionStatus (

    @SerialName(value = "profileId")
    val profileId: kotlin.String,

    @Contextual @SerialName(value = "status")
    val status: ConnectionStatus

) {


}

