/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param buildNumber 
 * @param purchaseDate ISO8601 timestamp string.
 */
@Serializable

data class OriginalPurchase (

    @SerialName(value = "buildNumber")
    val buildNumber: kotlin.Int,

    /* ISO8601 timestamp string. */
    @SerialName(value = "purchaseDate")
    val purchaseDate: kotlin.String

) {


}

