/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.AppProfileHeader
import com.algoritmico.passepartout.abi.Event

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param headers 
 */
@Serializable

@SerialName(value = "ProfileEventRefresh")
data class ProfileEventRefresh (

    @Contextual @SerialName(value = "headers")
    val headers: kotlin.collections.Map<kotlin.String, AppProfileHeader>

) : Event() {


}

