/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi

import com.algoritmico.passepartout.abi.Event
import io.partout.abi.TaggedProfile

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param profile 
 * @param previous 
 */
@Serializable

@SerialName(value = "ProfileEventSave")
data class ProfileEventSave (

    @Contextual @SerialName(value = "profile")
    val profile: TaggedProfile,

    @Contextual @SerialName(value = "previous")
    val previous: TaggedProfile? = null

) : Event() {


}

