/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param disconnectsOnSleep 
 * @param includesAllNetworks 
 */
@Serializable

data class ProfileBehavior (

    @SerialName(value = "disconnectsOnSleep")
    val disconnectsOnSleep: kotlin.Boolean,

    @SerialName(value = "includesAllNetworks")
    val includesAllNetworks: kotlin.Boolean? = null

) {


}

