/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.abi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param major 
 * @param minor 
 * @param patch 
 */
@Serializable

data class SemanticVersion (

    @SerialName(value = "major")
    val major: kotlin.Int,

    @SerialName(value = "minor")
    val minor: kotlin.Int,

    @SerialName(value = "patch")
    val patch: kotlin.Int

) {


}

