/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.AppUserLevel
import com.algoritmico.passepartout.models.DistributionTarget

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param distributionTarget 
 * @param displayName 
 * @param versionNumber 
 * @param buildNumber 
 * @param customUserLevel 
 * @param bundleStrings 
 */
@Serializable

data class AppBundle (

    @Contextual @SerialName(value = "distributionTarget")
    val distributionTarget: DistributionTarget,

    @SerialName(value = "displayName")
    val displayName: kotlin.String,

    @SerialName(value = "versionNumber")
    val versionNumber: kotlin.String,

    @SerialName(value = "buildNumber")
    val buildNumber: kotlin.Int,

    @Contextual @SerialName(value = "customUserLevel")
    val customUserLevel: AppUserLevel? = null,

    @SerialName(value = "bundleStrings")
    val bundleStrings: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

