/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.algoritmico.passepartout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: configFlags,cryptoBackend,deviceId,dnsFallsBack,experimental,extensiveLogging,lastCheckedVersion,lastCheckedVersionDate,lastUsedProfileId,logsPrivateData,skipsPurchases
 */
@Serializable
enum class AppPreferenceKey(val value: kotlin.String) {

    @SerialName(value = "configFlags")
    configFlags("configFlags"),

    @SerialName(value = "cryptoBackend")
    cryptoBackend("cryptoBackend"),

    @SerialName(value = "deviceId")
    deviceId("deviceId"),

    @SerialName(value = "dnsFallsBack")
    dnsFallsBack("dnsFallsBack"),

    @SerialName(value = "experimental")
    experimental("experimental"),

    @SerialName(value = "extensiveLogging")
    extensiveLogging("extensiveLogging"),

    @SerialName(value = "lastCheckedVersion")
    lastCheckedVersion("lastCheckedVersion"),

    @SerialName(value = "lastCheckedVersionDate")
    lastCheckedVersionDate("lastCheckedVersionDate"),

    @SerialName(value = "lastUsedProfileId")
    lastUsedProfileId("lastUsedProfileId"),

    @SerialName(value = "logsPrivateData")
    logsPrivateData("logsPrivateData"),

    @SerialName(value = "skipsPurchases")
    skipsPurchases("skipsPurchases");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AppPreferenceKey) "$data" else null

        /**
         * Returns a valid [AppPreferenceKey] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AppPreferenceKey? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


