/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.ConfigFlag
import com.algoritmico.passepartout.models.ExperimentalPreferences

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param configFlags 
 * @param dnsFallsBack 
 * @param experimental 
 * @param extensiveLogging 
 * @param logsPrivateData 
 * @param newProfileEncoding 
 * @param relaxedVerification 
 * @param skipsPurchases 
 * @param deviceId 
 * @param lastCheckedVersionTimestamp 64-bit millis since UNIX epoch.
 * @param lastCheckedVersion 
 * @param lastUsedProfileUUID 
 */
@Serializable

data class AppPreferences (

    @SerialName(value = "configFlags")
    val configFlags: kotlin.collections.List<@Contextual ConfigFlag>,

    @SerialName(value = "dnsFallsBack")
    val dnsFallsBack: kotlin.Boolean,

    @SerialName(value = "experimental")
    val experimental: ExperimentalPreferences,

    @SerialName(value = "extensiveLogging")
    val extensiveLogging: kotlin.Boolean,

    @SerialName(value = "logsPrivateData")
    val logsPrivateData: kotlin.Boolean,

    @SerialName(value = "newProfileEncoding")
    val newProfileEncoding: kotlin.Boolean,

    @SerialName(value = "relaxedVerification")
    val relaxedVerification: kotlin.Boolean,

    @SerialName(value = "skipsPurchases")
    val skipsPurchases: kotlin.Boolean,

    @SerialName(value = "deviceId")
    val deviceId: kotlin.String? = null,

    /* 64-bit millis since UNIX epoch. */
    @SerialName(value = "lastCheckedVersionTimestamp")
    val lastCheckedVersionTimestamp: kotlin.Long? = null,

    @SerialName(value = "lastCheckedVersion")
    val lastCheckedVersion: kotlin.String? = null,

    @SerialName(value = "lastUsedProfileUUID")
    val lastUsedProfileUUID: kotlin.String? = null

) {


}

