/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.algoritmico.passepartout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * New configuration keys use a fixed YYYYMM suffix for the month when the feature was introduced. Never reuse a key for an unrelated feature.
 *
 * Values: appNotWorking,experimentalDaemon_202610,experimentalDaemonOpenVPN_202610,experimentalDaemonWireGuard_202610,unknown
 */
@Serializable
enum class ConfigFlag(val value: kotlin.String) {

    @SerialName(value = "appNotWorking")
    appNotWorking("appNotWorking"),

    @SerialName(value = "experimentalDaemon_202610")
    experimentalDaemon_202610("experimentalDaemon_202610"),

    @SerialName(value = "experimentalDaemonOpenVPN_202610")
    experimentalDaemonOpenVPN_202610("experimentalDaemonOpenVPN_202610"),

    @SerialName(value = "experimentalDaemonWireGuard_202610")
    experimentalDaemonWireGuard_202610("experimentalDaemonWireGuard_202610"),

    @SerialName(value = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ConfigFlag) "$data" else null

        /**
         * Returns a valid [ConfigFlag] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ConfigFlag? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


