/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.ConfigFlag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ignoredConfigFlags 
 * @param enabledConfigFlags 
 */
@Serializable

data class ExperimentalPreferences (

    @SerialName(value = "ignoredConfigFlags")
    val ignoredConfigFlags: kotlin.collections.List<@Contextual ConfigFlag>,

    @SerialName(value = "enabledConfigFlags")
    val enabledConfigFlags: kotlin.collections.List<@Contextual ConfigFlag>

) {


}

