/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.Event
import com.algoritmico.passepartout.models.OriginalPurchase

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param products 
 * @param isBeta 
 * @param originalPurchase 
 */
@Serializable

@SerialName(value = "IAPEventNewReceipt")
data class IAPEventNewReceipt (

    @SerialName(value = "products")
    val products: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "isBeta")
    val isBeta: kotlin.Boolean,

    @SerialName(value = "originalPurchase")
    val originalPurchase: OriginalPurchase? = null

) : Event() {


}

