/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param filename 
 * @param content 
 */
@Serializable

data class IssueAttachment (

    @SerialName(value = "filename")
    val filename: kotlin.String,

    @SerialName(value = "content")
    val content: kotlin.ByteArray

) {


}

