/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.IssueAttachment

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param comment 
 * @param purchasedProducts 
 * @param providerLastUpdates 
 * @param attachments 
 * @param osLine 
 * @param appLine 
 * @param deviceLine 
 */
@Serializable

data class Issue (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "comment")
    val comment: kotlin.String,

    @SerialName(value = "purchasedProducts")
    val purchasedProducts: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "providerLastUpdates")
    val providerLastUpdates: kotlin.collections.Map<kotlin.String, kotlin.Long>,

    @SerialName(value = "attachments")
    val attachments: kotlin.collections.List<IssueAttachment>,

    @SerialName(value = "osLine")
    val osLine: kotlin.String,

    @SerialName(value = "appLine")
    val appLine: kotlin.String? = null,

    @SerialName(value = "deviceLine")
    val deviceLine: kotlin.String? = null

) {


}

