/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param buildNumber 
 * @param purchaseDate 64-bit millis since UNIX epoch.
 */
@Serializable

data class OriginalPurchase (

    @SerialName(value = "buildNumber")
    val buildNumber: kotlin.Int,

    /* 64-bit millis since UNIX epoch. */
    @SerialName(value = "purchaseDate")
    val purchaseDate: kotlin.Long

) {


}

