/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.Event

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ids 
 */
@Serializable

@SerialName(value = "ProfileEventDelete")
data class ProfileEventDelete (

    @SerialName(value = "ids")
    val ids: kotlin.collections.List<kotlin.String>

) : Event() {


}

