/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.AppProfileHeader
import com.algoritmico.passepartout.models.Event

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param headers 
 */
@Serializable

@SerialName(value = "ProfileEventRefresh")
data class ProfileEventRefresh (

    @Contextual @SerialName(value = "headers")
    val headers: kotlin.collections.Map<kotlin.String, AppProfileHeader>

) : Event() {


}

