/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.SemanticVersion

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param version 
 * @param url 
 */
@Serializable

data class VersionRelease (

    @SerialName(value = "version")
    val version: SemanticVersion,

    @SerialName(value = "url")
    val url: kotlin.String

) {


}

