/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.algoritmico.passepartout.models

import com.algoritmico.passepartout.models.Event
import com.algoritmico.passepartout.models.WebFileUpload

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param file 
 */
@Serializable

@SerialName(value = "WebReceiverEventNewUpload")
data class WebReceiverEventNewUpload (

    @SerialName(value = "file")
    val file: WebFileUpload

) : Event() {


}

