// SPDX-License-Identifier: GPL-3.0
// Copyright 2026 SigmaDev

/// Converts upstream's Apple string catalogues into one Dartvel catalogue file.
///
///     dart run tool/import_strings.dart
///
/// Reads `app-apple/Sources/AppStrings/Resources/<locale>.lproj/Localizable.strings`
/// and writes `lib/l10n/strings.g.dart`. It holds one `DVTranslationKey` per
/// upstream key, named after the key (`views.app.toolbar.import_file` becomes
/// `Strings.viewsAppToolbarImportFile`), and one `DVTranslationCatalog` per locale.
/// Apple placeholders (`%@`, `%d`, `%1$@`) become `{0}`, `{1}`... in argument order.
library;

import 'dart:io';

final RegExp _line = RegExp(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)";\s*$');
final RegExp _placeholder = RegExp(r'%(?:(\d+)\$)?(?:@|d|ld|lu|u)');

String _unescape(String value) => value
    .replaceAll(r'\"', '"')
    .replaceAll(r'\n', '\n')
    .replaceAll(r'\\', r'\');

String _placeholders(String value) {
  var position = 0;
  return value.replaceAllMapped(_placeholder, (match) {
    final explicit = match.group(1);
    final index = explicit != null ? int.parse(explicit) - 1 : position++;
    return '{$index}';
  });
}

String _identifier(String key) {
  final parts = key.split(RegExp(r'[._\-]')).where((part) => part.isNotEmpty).toList();
  final buffer = StringBuffer(parts.first);
  for (final part in parts.skip(1)) {
    buffer.write(part[0].toUpperCase() + part.substring(1));
  }
  var name = buffer.toString();
  if (RegExp(r'^\d').hasMatch(name)) name = 'k$name';
  return name;
}

String _literal(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}

Map<String, String> _read(File file) {
  final entries = <String, String>{};
  for (final line in file.readAsLinesSync()) {
    final match = _line.firstMatch(line.trim());
    if (match == null) continue;
    entries[_unescape(match.group(1)!)] = _placeholders(_unescape(match.group(2)!));
  }
  return entries;
}

void main() {
  final resources = Directory('../app-apple/Sources/AppStrings/Resources');
  final locales = <String, Map<String, String>>{};
  for (final entity in resources.listSync()..sort((a, b) => a.path.compareTo(b.path))) {
    if (entity is! Directory || !entity.path.endsWith('.lproj')) continue;
    final locale = entity.uri.pathSegments.where((s) => s.isNotEmpty).last.replaceAll('.lproj', '');
    final file = File('${entity.path}/Localizable.strings');
    if (file.existsSync()) locales[locale] = _read(file);
  }
  final english = locales['en']!;
  final out = StringBuffer()
    ..writeln('// SPDX-License-Identifier: GPL-3.0')
    ..writeln('// GENERATED by tool/import_strings.dart from upstream Localizable.strings. Do not edit.')
    ..writeln('// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars')
    ..writeln()
    ..writeln("import '../dartvel_client/dartvel_client.dart';")
    ..writeln()
    ..writeln('/// Every upstream string key, named after the key.')
    ..writeln('abstract final class Strings {');
  final names = <String>{};
  for (final key in english.keys) {
    final name = _identifier(key);
    if (!names.add(name)) throw StateError('Duplicate identifier $name for $key');
    out.writeln('  /// ${english[key]!.replaceAll('\n', ' ')}');
    out.writeln("  static const DVTranslationKey $name = DVTranslationKey('$key');");
  }
  out
    ..writeln('}')
    ..writeln()
    ..writeln('/// Upstream locale code to its catalogue. English is the fallback.')
    ..writeln('final Map<String, DVTranslationCatalog> stringCatalogs = <String, DVTranslationCatalog>{');
  for (final entry in locales.entries) {
    out.writeln("  '${entry.key}': const DVTranslationCatalog(locale: LocaleTag('${entry.key}'), messages: <DVTranslationKey, String>{");
    for (final message in entry.value.entries) {
      if (!english.containsKey(message.key)) continue;
      out.writeln('    Strings.${_identifier(message.key)}: ${_literal(message.value)},');
    }
    out.writeln('  }),');
  }
  out.writeln('};');
  Directory('lib/l10n').createSync(recursive: true);
  File('lib/l10n/strings.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('${english.length} keys, ${locales.length} locales');
}
