//
// OpenAPIProfileEventShouldReconnect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileEventShouldReconnect: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case profileEventShouldReconnect = "ProfileEventShouldReconnect"
    }
    public let type: OpenAPIType = .profileEventShouldReconnect
    public var profile: TaggedProfile

    public init(profile: TaggedProfile) {
        self.profile = profile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case profile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(profile, forKey: .profile)
    }
}

