//
// OpenAPIAppConstantsApi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsApi: Sendable, Codable, Hashable {

    public var timeoutInterval: Double
    public var versionRateLimit: Double
    public var refreshInfrastructureRateLimit: Double

    public init(timeoutInterval: Double, versionRateLimit: Double, refreshInfrastructureRateLimit: Double) {
        self.timeoutInterval = timeoutInterval
        self.versionRateLimit = versionRateLimit
        self.refreshInfrastructureRateLimit = refreshInfrastructureRateLimit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeoutInterval
        case versionRateLimit
        case refreshInfrastructureRateLimit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeoutInterval, forKey: .timeoutInterval)
        try container.encode(versionRateLimit, forKey: .versionRateLimit)
        try container.encode(refreshInfrastructureRateLimit, forKey: .refreshInfrastructureRateLimit)
    }
}

