//
// OpenAPIAppConstantsTunnelVerification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsTunnelVerification: Sendable, Codable, Hashable {

    public var production: OpenAPIAppConstantsTunnelVerificationParameters
    public var beta: OpenAPIAppConstantsTunnelVerificationParameters

    public init(production: OpenAPIAppConstantsTunnelVerificationParameters, beta: OpenAPIAppConstantsTunnelVerificationParameters) {
        self.production = production
        self.beta = beta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case production
        case beta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(production, forKey: .production)
        try container.encode(beta, forKey: .beta)
    }
}

