//
// OpenAPIModuleType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIModuleType: String, Sendable, Codable, CaseIterable {
    case DNS = "DNS"
    case HTTPProxy = "HTTPProxy"
    case IP = "IP"
    case OnDemand = "OnDemand"
    case OpenVPN = "OpenVPN"
    case WireGuard = "WireGuard"
}
