//
// OpenAPIAppConstantsTunnelVerificationParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsTunnelVerificationParameters: Sendable, Codable, Hashable {

    public var delay: Double
    public var interval: Double
    public var attempts: Int
    public var retryInterval: Double

    public init(delay: Double, interval: Double, attempts: Int, retryInterval: Double) {
        self.delay = delay
        self.interval = interval
        self.attempts = attempts
        self.retryInterval = retryInterval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case delay
        case interval
        case attempts
        case retryInterval
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(delay, forKey: .delay)
        try container.encode(interval, forKey: .interval)
        try container.encode(attempts, forKey: .attempts)
        try container.encode(retryInterval, forKey: .retryInterval)
    }
}

