//
// OpenAPIAppConstantsLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsLog: Sendable, Codable, Hashable {

    public var formatter: OpenAPIAppConstantsLogFormatter
    public var sinceLast: Double
    public var options: OpenAPILocalLoggerOptions

    public init(formatter: OpenAPIAppConstantsLogFormatter, sinceLast: Double, options: OpenAPILocalLoggerOptions) {
        self.formatter = formatter
        self.sinceLast = sinceLast
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case formatter
        case sinceLast
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(formatter, forKey: .formatter)
        try container.encode(sinceLast, forKey: .sinceLast)
        try container.encode(options, forKey: .options)
    }
}

