//
// OpenAPIAppTunnelInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppTunnelInfo: Sendable, Codable, Hashable {

    public var id: String
    public var status: OpenAPIAppTunnelStatus
    public var onDemand: Bool

    public init(id: String, status: OpenAPIAppTunnelStatus, onDemand: Bool) {
        self.id = id
        self.status = status
        self.onDemand = onDemand
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
        case onDemand
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(onDemand, forKey: .onDemand)
    }
}


extension OpenAPIAppTunnelInfo: Identifiable {}
