//
// OpenAPILocalLoggerOptionsMaxLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

/** DebugLog.Level (0&#x3D;debug, 1&#x3D;info, 2&#x3D;warning, 3&#x3D;error) */
public enum OpenAPILocalLoggerOptionsMaxLevel: Int, Sendable, Codable, CaseIterable {
    case debug = 0
    case info = 1
    case warning = 2
    case error = 3
}
