//
// OpenAPIAppTunnelInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppTunnelInfo: Sendable, Codable, Hashable {

    public var rawId: String
    public var isEnabled: Bool
    public var status: OpenAPIAppProfileStatus
    public var rawTunnelStatus: String
    public var onDemand: Bool
    public var transfer: OpenAPIProfileTransfer?
    public var rawLastErrorCode: String?

    public init(rawId: String, isEnabled: Bool, status: OpenAPIAppProfileStatus, rawTunnelStatus: String, onDemand: Bool, transfer: OpenAPIProfileTransfer? = nil, rawLastErrorCode: String? = nil) {
        self.rawId = rawId
        self.isEnabled = isEnabled
        self.status = status
        self.rawTunnelStatus = rawTunnelStatus
        self.onDemand = onDemand
        self.transfer = transfer
        self.rawLastErrorCode = rawLastErrorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rawId
        case isEnabled
        case status
        case rawTunnelStatus
        case onDemand
        case transfer
        case rawLastErrorCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rawId, forKey: .rawId)
        try container.encode(isEnabled, forKey: .isEnabled)
        try container.encode(status, forKey: .status)
        try container.encode(rawTunnelStatus, forKey: .rawTunnelStatus)
        try container.encode(onDemand, forKey: .onDemand)
        try container.encodeIfPresent(transfer, forKey: .transfer)
        try container.encodeIfPresent(rawLastErrorCode, forKey: .rawLastErrorCode)
    }
}

