//
// OpenAPIAppConstants.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstants: Sendable, Codable, Hashable {

    public var deviceIdLength: Int
    public var containers: OpenAPIAppConstantsContainers
    public var websites: OpenAPIAppConstantsWebsites
    public var github: OpenAPIAppConstantsGithub
    public var emails: OpenAPIAppConstantsEmails
    public var formats: OpenAPIAppConstantsFormats
    public var tunnel: OpenAPIAppConstantsTunnel
    public var api: OpenAPIAppConstantsApi
    public var iap: OpenAPIAppConstantsIap
    public var webReceiver: OpenAPIAppConstantsWebReceiver
    public var log: OpenAPIAppConstantsLog

    public init(deviceIdLength: Int, containers: OpenAPIAppConstantsContainers, websites: OpenAPIAppConstantsWebsites, github: OpenAPIAppConstantsGithub, emails: OpenAPIAppConstantsEmails, formats: OpenAPIAppConstantsFormats, tunnel: OpenAPIAppConstantsTunnel, api: OpenAPIAppConstantsApi, iap: OpenAPIAppConstantsIap, webReceiver: OpenAPIAppConstantsWebReceiver, log: OpenAPIAppConstantsLog) {
        self.deviceIdLength = deviceIdLength
        self.containers = containers
        self.websites = websites
        self.github = github
        self.emails = emails
        self.formats = formats
        self.tunnel = tunnel
        self.api = api
        self.iap = iap
        self.webReceiver = webReceiver
        self.log = log
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceIdLength
        case containers
        case websites
        case github
        case emails
        case formats
        case tunnel
        case api
        case iap
        case webReceiver
        case log
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceIdLength, forKey: .deviceIdLength)
        try container.encode(containers, forKey: .containers)
        try container.encode(websites, forKey: .websites)
        try container.encode(github, forKey: .github)
        try container.encode(emails, forKey: .emails)
        try container.encode(formats, forKey: .formats)
        try container.encode(tunnel, forKey: .tunnel)
        try container.encode(api, forKey: .api)
        try container.encode(iap, forKey: .iap)
        try container.encode(webReceiver, forKey: .webReceiver)
        try container.encode(log, forKey: .log)
    }
}

