//
// OpenAPIAppConstantsLogFilenames.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsLogFilenames: Sendable, Codable, Hashable {

    public var app: String
    public var tunnel: String

    public init(app: String, tunnel: String) {
        self.app = app
        self.tunnel = tunnel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case tunnel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
        try container.encode(tunnel, forKey: .tunnel)
    }
}

