//
// OpenAPIAppConstantsWebsites.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsWebsites: Sendable, Codable, Hashable {

    public var homeURL: URL
    public var eulaURL: URL
    public var appStoreDownloadURL: URL
    public var macDownloadURL: URL
    public var configTTL: Double

    public init(homeURL: URL, eulaURL: URL, appStoreDownloadURL: URL, macDownloadURL: URL, configTTL: Double) {
        self.homeURL = homeURL
        self.eulaURL = eulaURL
        self.appStoreDownloadURL = appStoreDownloadURL
        self.macDownloadURL = macDownloadURL
        self.configTTL = configTTL
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case homeURL
        case eulaURL
        case appStoreDownloadURL
        case macDownloadURL
        case configTTL
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(homeURL, forKey: .homeURL)
        try container.encode(eulaURL, forKey: .eulaURL)
        try container.encode(appStoreDownloadURL, forKey: .appStoreDownloadURL)
        try container.encode(macDownloadURL, forKey: .macDownloadURL)
        try container.encode(configTTL, forKey: .configTTL)
    }
}

