//
// OpenAPITunnelEventRefresh.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPITunnelEventRefresh: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case tunnelEventRefresh = "TunnelEventRefresh"
    }
    public let type: OpenAPIType = .tunnelEventRefresh
    public var active: [String: OpenAPIAppTunnelInfo]

    public init(active: [String: OpenAPIAppTunnelInfo]) {
        self.active = active
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case active
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(active, forKey: .active)
    }
}

