//
// OpenAPILocalLoggerOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPILocalLoggerOptions: Sendable, Codable, Hashable {

    public var maxLevel: OpenAPILocalLoggerOptionsMaxLevel
    /** Maximum size in bytes */
    public var maxSize: Int
    public var maxBufferedLines: Int
    /** Optional maximum age in seconds */
    public var maxAge: Double?

    public init(maxLevel: OpenAPILocalLoggerOptionsMaxLevel, maxSize: Int, maxBufferedLines: Int, maxAge: Double? = nil) {
        self.maxLevel = maxLevel
        self.maxSize = maxSize
        self.maxBufferedLines = maxBufferedLines
        self.maxAge = maxAge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxLevel
        case maxSize
        case maxBufferedLines
        case maxAge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(maxLevel, forKey: .maxLevel)
        try container.encode(maxSize, forKey: .maxSize)
        try container.encode(maxBufferedLines, forKey: .maxBufferedLines)
        try container.encodeIfPresent(maxAge, forKey: .maxAge)
    }
}

