//
// OpenAPIMixedEventShouldUpdatePreferences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIMixedEventShouldUpdatePreferences: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case mixedEventShouldUpdatePreferences = "MixedEventShouldUpdatePreferences"
    }
    public let type: OpenAPIType = .mixedEventShouldUpdatePreferences
    public var preferences: OpenAPIAppPreferences
    public var fields: [OpenAPIAppPreferenceKey]

    public init(preferences: OpenAPIAppPreferences, fields: [OpenAPIAppPreferenceKey]) {
        self.preferences = preferences
        self.fields = fields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case preferences
        case fields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(preferences, forKey: .preferences)
        try container.encode(fields, forKey: .fields)
    }
}

