//
// OpenAPIProfileEventSave.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileEventSave: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case profileEventSave = "ProfileEventSave"
    }
    public let type: OpenAPIType = .profileEventSave

    public init() {
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
    }
}

