//
// OpenAPIChangelogEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIChangelogEntry: Sendable, Codable, Hashable {

    public var id: Int
    public var comment: String
    public var issue: Int?

    public init(id: Int, comment: String, issue: Int? = nil) {
        self.id = id
        self.comment = comment
        self.issue = issue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case comment
        case issue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(comment, forKey: .comment)
        try container.encodeIfPresent(issue, forKey: .issue)
    }
}


extension OpenAPIChangelogEntry: Identifiable {}
