//
// OpenAPIAppTunnelInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppTunnelInfo: Sendable, Codable, Hashable {

    public var id: String
    public var isEnabled: Bool
    public var status: OpenAPIAppProfileStatus
    public var onDemand: Bool
    public var transfer: OpenAPIProfileTransfer?
    public var lastErrorCode: String?

    public init(id: String, isEnabled: Bool, status: OpenAPIAppProfileStatus, onDemand: Bool, transfer: OpenAPIProfileTransfer? = nil, lastErrorCode: String? = nil) {
        self.id = id
        self.isEnabled = isEnabled
        self.status = status
        self.onDemand = onDemand
        self.transfer = transfer
        self.lastErrorCode = lastErrorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case isEnabled
        case status
        case onDemand
        case transfer
        case lastErrorCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(isEnabled, forKey: .isEnabled)
        try container.encode(status, forKey: .status)
        try container.encode(onDemand, forKey: .onDemand)
        try container.encodeIfPresent(transfer, forKey: .transfer)
        try container.encodeIfPresent(lastErrorCode, forKey: .lastErrorCode)
    }
}


extension OpenAPIAppTunnelInfo: Identifiable {}
