//
// OpenAPIProfileTransfer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileTransfer: Sendable, Codable, Hashable {

    public var received: Int = 0
    public var sent: Int = 0

    public init(received: Int = 0, sent: Int = 0) {
        self.received = received
        self.sent = sent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case received
        case sent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(received, forKey: .received)
        try container.encode(sent, forKey: .sent)
    }
}

