//
// OpenAPIAppPreference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIAppPreference: String, Sendable, Codable, CaseIterable {
    case deviceId = "deviceId"
    case configFlags = "configFlags"
    case dnsFallsBack = "dnsFallsBack"
    case dnsFallbackServers = "dnsFallbackServers"
    case experimental = "experimental"
    case extensiveLogging = "extensiveLogging"
    case lastCheckedVersionDate = "lastCheckedVersionDate"
    case lastCheckedVersion = "lastCheckedVersion"
    case lastUsedProfileId = "lastUsedProfileId"
    case logsPrivateData = "logsPrivateData"
    case newProfileEncoding = "newProfileEncoding"
    case relaxedVerification = "relaxedVerification"
    case skipsPurchases = "skipsPurchases"
}
