//
// OpenAPIAppProfileHeader.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppProfileHeader: Sendable, Codable, Hashable {

    public var id: String
    public var name: String
    public var moduleTypes: [OpenAPIModuleType]
    public var primaryModuleType: OpenAPIModuleType?
    public var secondaryModuleTypes: [OpenAPIModuleType]
    public var providerInfo: OpenAPIProviderInfo?
    public var fingerprint: String
    public var sharingFlags: [OpenAPIProfileSharingFlag]
    public var requiredFeatures: [OpenAPIAppFeature]

    public init(id: String, name: String, moduleTypes: [OpenAPIModuleType], primaryModuleType: OpenAPIModuleType? = nil, secondaryModuleTypes: [OpenAPIModuleType], providerInfo: OpenAPIProviderInfo? = nil, fingerprint: String, sharingFlags: [OpenAPIProfileSharingFlag], requiredFeatures: [OpenAPIAppFeature]) {
        self.id = id
        self.name = name
        self.moduleTypes = moduleTypes
        self.primaryModuleType = primaryModuleType
        self.secondaryModuleTypes = secondaryModuleTypes
        self.providerInfo = providerInfo
        self.fingerprint = fingerprint
        self.sharingFlags = sharingFlags
        self.requiredFeatures = requiredFeatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case moduleTypes
        case primaryModuleType
        case secondaryModuleTypes
        case providerInfo
        case fingerprint
        case sharingFlags
        case requiredFeatures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(moduleTypes, forKey: .moduleTypes)
        try container.encodeIfPresent(primaryModuleType, forKey: .primaryModuleType)
        try container.encode(secondaryModuleTypes, forKey: .secondaryModuleTypes)
        try container.encodeIfPresent(providerInfo, forKey: .providerInfo)
        try container.encode(fingerprint, forKey: .fingerprint)
        try container.encode(sharingFlags, forKey: .sharingFlags)
        try container.encode(requiredFeatures, forKey: .requiredFeatures)
    }
}


extension OpenAPIAppProfileHeader: Identifiable {}
