//
// OpenAPIMixedEventUpdatedPreferences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIMixedEventUpdatedPreferences: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case mixedEventUpdatedPreferences = "MixedEventUpdatedPreferences"
    }
    public let type: OpenAPIType = .mixedEventUpdatedPreferences
    public var patch: OpenAPIAppPreferencesPatch

    public init(patch: OpenAPIAppPreferencesPatch) {
        self.patch = patch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case patch
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(patch, forKey: .patch)
    }
}

