//
// OpenAPIAppConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConfiguration: Sendable, Codable, Hashable {

    public var bundle: OpenAPIAppBundle
    public var constants: OpenAPIAppConstants

    public init(bundle: OpenAPIAppBundle, constants: OpenAPIAppConstants) {
        self.bundle = bundle
        self.constants = constants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bundle
        case constants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bundle, forKey: .bundle)
        try container.encode(constants, forKey: .constants)
    }
}

