//
// OpenAPIIAPEventLoadReceipt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIIAPEventLoadReceipt: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case iapeventloadreceipt = "IAPEventLoadReceipt"
    }
    public let type: OpenAPIType = .iapeventloadreceipt
    public var isLoading: Bool

    public init(isLoading: Bool) {
        self.isLoading = isLoading
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case isLoading
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(isLoading, forKey: .isLoading)
    }
}

