//
// OpenAPIAppConstantsTunnel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsTunnel: Sendable, Codable, Hashable {

    public var profileTitleFormat: String
    public var refreshInterval: Double
    public var dnsFallbackServers: [String]
    public var verification: OpenAPIAppConstantsTunnelVerification

    public init(profileTitleFormat: String, refreshInterval: Double, dnsFallbackServers: [String], verification: OpenAPIAppConstantsTunnelVerification) {
        self.profileTitleFormat = profileTitleFormat
        self.refreshInterval = refreshInterval
        self.dnsFallbackServers = dnsFallbackServers
        self.verification = verification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profileTitleFormat
        case refreshInterval
        case dnsFallbackServers
        case verification
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profileTitleFormat, forKey: .profileTitleFormat)
        try container.encode(refreshInterval, forKey: .refreshInterval)
        try container.encode(dnsFallbackServers, forKey: .dnsFallbackServers)
        try container.encode(verification, forKey: .verification)
    }
}

