//
// OpenAPIOnConnectionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIOnConnectionStatus: Sendable, Codable, Hashable {

    public var profileId: String
    public var status: ConnectionStatus

    public init(profileId: String, status: ConnectionStatus) {
        self.profileId = profileId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profileId
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profileId, forKey: .profileId)
        try container.encode(status, forKey: .status)
    }
}

