//
// OpenAPILocalLoggerOptionsMaxLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

/** DebugLog.Level (0&#x3D;fault, 1&#x3D;error, 2&#x3D;notice, 3&#x3D;info, 4&#x3D;debug) */
public enum OpenAPILocalLoggerOptionsMaxLevel: Int, Sendable, Codable, CaseIterable {
    case fault = 0
    case error = 1
    case notice = 2
    case info = 3
    case debug = 4
}
