//
// OpenAPIAppPreferencesPatchValues.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppPreferencesPatchValues: Sendable, Codable, Hashable {

    public var configFlags: [OpenAPIConfigFlag]?
    public var deviceId: String?
    public var dnsFallsBack: Bool?
    public var experimental: OpenAPIExperimentalPreferences?
    public var extensiveLogging: Bool?
    /** 64-bit millis since UNIX epoch. */
    public var lastCheckedVersionTimestamp: Int64?
    public var lastCheckedVersion: String?
    public var lastUsedProfileUUID: String?
    public var logsPrivateData: Bool?
    public var newProfileEncoding: Bool?
    public var relaxedVerification: Bool?
    public var skipsPurchases: Bool?

    public init(configFlags: [OpenAPIConfigFlag]? = nil, deviceId: String? = nil, dnsFallsBack: Bool? = nil, experimental: OpenAPIExperimentalPreferences? = nil, extensiveLogging: Bool? = nil, lastCheckedVersionTimestamp: Int64? = nil, lastCheckedVersion: String? = nil, lastUsedProfileUUID: String? = nil, logsPrivateData: Bool? = nil, newProfileEncoding: Bool? = nil, relaxedVerification: Bool? = nil, skipsPurchases: Bool? = nil) {
        self.configFlags = configFlags
        self.deviceId = deviceId
        self.dnsFallsBack = dnsFallsBack
        self.experimental = experimental
        self.extensiveLogging = extensiveLogging
        self.lastCheckedVersionTimestamp = lastCheckedVersionTimestamp
        self.lastCheckedVersion = lastCheckedVersion
        self.lastUsedProfileUUID = lastUsedProfileUUID
        self.logsPrivateData = logsPrivateData
        self.newProfileEncoding = newProfileEncoding
        self.relaxedVerification = relaxedVerification
        self.skipsPurchases = skipsPurchases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configFlags
        case deviceId
        case dnsFallsBack
        case experimental
        case extensiveLogging
        case lastCheckedVersionTimestamp
        case lastCheckedVersion
        case lastUsedProfileUUID
        case logsPrivateData
        case newProfileEncoding
        case relaxedVerification
        case skipsPurchases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(configFlags, forKey: .configFlags)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(dnsFallsBack, forKey: .dnsFallsBack)
        try container.encodeIfPresent(experimental, forKey: .experimental)
        try container.encodeIfPresent(extensiveLogging, forKey: .extensiveLogging)
        try container.encodeIfPresent(lastCheckedVersionTimestamp, forKey: .lastCheckedVersionTimestamp)
        try container.encodeIfPresent(lastCheckedVersion, forKey: .lastCheckedVersion)
        try container.encodeIfPresent(lastUsedProfileUUID, forKey: .lastUsedProfileUUID)
        try container.encodeIfPresent(logsPrivateData, forKey: .logsPrivateData)
        try container.encodeIfPresent(newProfileEncoding, forKey: .newProfileEncoding)
        try container.encodeIfPresent(relaxedVerification, forKey: .relaxedVerification)
        try container.encodeIfPresent(skipsPurchases, forKey: .skipsPurchases)
    }
}

