//
// OpenAPIProviderInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProviderInfo: Sendable, Codable, Hashable {

    public var providerId: String
    public var countryCode: String?

    public init(providerId: String, countryCode: String? = nil) {
        self.providerId = providerId
        self.countryCode = countryCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerId
        case countryCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(providerId, forKey: .providerId)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
    }
}

