//
// OpenAPIProfileBehavior.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileBehavior: Sendable, Codable, Hashable {

    public var disconnectsOnSleep: Bool
    public var includesAllNetworks: Bool?

    public init(disconnectsOnSleep: Bool, includesAllNetworks: Bool? = nil) {
        self.disconnectsOnSleep = disconnectsOnSleep
        self.includesAllNetworks = includesAllNetworks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case disconnectsOnSleep
        case includesAllNetworks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(disconnectsOnSleep, forKey: .disconnectsOnSleep)
        try container.encodeIfPresent(includesAllNetworks, forKey: .includesAllNetworks)
    }
}

