//
// OpenAPIConfigFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIConfigFlag: String, Sendable, Codable, CaseIterable {
    case allowsRelaxedVerification = "allowsRelaxedVerification"
    case appNotWorking = "appNotWorking"
    case neSocketUDP = "neSocketUDP"
    case neSocketTCP = "neSocketTCP"
    case newProfileEncoding = "newProfileEncoding"
    case unknown = "unknown"
}
