//
// OpenAPIConfigFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIConfigFlag: String, Sendable, Codable, CaseIterable {
    case allowsRelaxedVerification = "allowsRelaxedVerification"
    case appNotWorking = "appNotWorking"
    case bsdSockets = "bsdSockets"
    case forcesRelaxedVerification = "forcesRelaxedVerification"
    case newProfileEncoding = "newProfileEncoding"
    case ovpnCrossV2 = "ovpnCrossV2"
    case wgCrossV2 = "wgCrossV2"
    case unknown = "unknown"
}
