//
// OpenAPIAppBundle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppBundle: Sendable, Codable, Hashable {

    public var distributionTarget: OpenAPIDistributionTarget
    public var displayName: String
    public var versionNumber: String
    public var buildNumber: Int
    public var customUserLevel: OpenAPIAppUserLevel?
    public var bundleStrings: [String: String]?

    public init(distributionTarget: OpenAPIDistributionTarget, displayName: String, versionNumber: String, buildNumber: Int, customUserLevel: OpenAPIAppUserLevel? = nil, bundleStrings: [String: String]? = nil) {
        self.distributionTarget = distributionTarget
        self.displayName = displayName
        self.versionNumber = versionNumber
        self.buildNumber = buildNumber
        self.customUserLevel = customUserLevel
        self.bundleStrings = bundleStrings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case distributionTarget
        case displayName
        case versionNumber
        case buildNumber
        case customUserLevel
        case bundleStrings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(distributionTarget, forKey: .distributionTarget)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(versionNumber, forKey: .versionNumber)
        try container.encode(buildNumber, forKey: .buildNumber)
        try container.encodeIfPresent(customUserLevel, forKey: .customUserLevel)
        try container.encodeIfPresent(bundleStrings, forKey: .bundleStrings)
    }
}

