//
// OpenAPIAppConstantsIap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsIap: Sendable, Codable, Hashable {

    public var productsTimeoutInterval: Double
    public var receiptInvalidationInterval: Double

    public init(productsTimeoutInterval: Double, receiptInvalidationInterval: Double) {
        self.productsTimeoutInterval = productsTimeoutInterval
        self.receiptInvalidationInterval = receiptInvalidationInterval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productsTimeoutInterval
        case receiptInvalidationInterval
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(productsTimeoutInterval, forKey: .productsTimeoutInterval)
        try container.encode(receiptInvalidationInterval, forKey: .receiptInvalidationInterval)
    }
}

