//
// OpenAPIAppPreferencesPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppPreferencesPatch: Sendable, Codable, Hashable {

    public var values: OpenAPIAppPreferencesPatchValues?
    public var fieldsToUnset: [OpenAPIAppPreferenceKey]?

    public init(values: OpenAPIAppPreferencesPatchValues? = nil, fieldsToUnset: [OpenAPIAppPreferenceKey]? = nil) {
        self.values = values
        self.fieldsToUnset = fieldsToUnset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case values
        case fieldsToUnset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(values, forKey: .values)
        try container.encodeIfPresent(fieldsToUnset, forKey: .fieldsToUnset)
    }
}

