//
// OpenAPIAppConstantsWebReceiver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsWebReceiver: Sendable, Codable, Hashable {

    public var port: Int
    public var passcodeLength: Int

    public init(port: Int, passcodeLength: Int) {
        self.port = port
        self.passcodeLength = passcodeLength
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case port
        case passcodeLength
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(port, forKey: .port)
        try container.encode(passcodeLength, forKey: .passcodeLength)
    }
}

