//
// OpenAPIProfileEventSave.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileEventSave: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case profileEventSave = "ProfileEventSave"
    }
    public let type: OpenAPIType = .profileEventSave
    public var profile: TaggedProfile
    public var previous: TaggedProfile?

    public init(profile: TaggedProfile, previous: TaggedProfile? = nil) {
        self.profile = profile
        self.previous = previous
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case profile
        case previous
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(profile, forKey: .profile)
        try container.encodeIfPresent(previous, forKey: .previous)
    }
}

