//
// OpenAPIWebFileUpload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIWebFileUpload: Sendable, Codable, Hashable {

    public var name: String
    public var contents: String

    public init(name: String, contents: String) {
        self.name = name
        self.contents = contents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case contents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(contents, forKey: .contents)
    }
}

