//
// OpenAPIProfileEventRefresh.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileEventRefresh: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case profileEventRefresh = "ProfileEventRefresh"
    }
    public let type: OpenAPIType = .profileEventRefresh
    public var headers: [String: OpenAPIAppProfileHeader]

    public init(headers: [String: OpenAPIAppProfileHeader]) {
        self.headers = headers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case headers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(headers, forKey: .headers)
    }
}

