//
// OpenAPIConfigBundlePlatform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIConfigBundlePlatform: String, Sendable, Codable, CaseIterable {
    case android = "android"
    case apple = "apple"
}
