//
// OpenAPIWebReceiverEventUploadFailure.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIWebReceiverEventUploadFailure: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case webReceiverEventUploadFailure = "WebReceiverEventUploadFailure"
    }
    public let type: OpenAPIType = .webReceiverEventUploadFailure
    public var error: String

    public init(error: String) {
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(error, forKey: .error)
    }
}

