//
// OpenAPIAppConstantsGithub.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsGithub: Sendable, Codable, Hashable {

    public var discussionsURL: URL
    public var issuesURL: URL
    public var rawURL: URL
    public var latestReleaseURL: URL

    public init(discussionsURL: URL, issuesURL: URL, rawURL: URL, latestReleaseURL: URL) {
        self.discussionsURL = discussionsURL
        self.issuesURL = issuesURL
        self.rawURL = rawURL
        self.latestReleaseURL = latestReleaseURL
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discussionsURL
        case issuesURL
        case rawURL
        case latestReleaseURL
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(discussionsURL, forKey: .discussionsURL)
        try container.encode(issuesURL, forKey: .issuesURL)
        try container.encode(rawURL, forKey: .rawURL)
        try container.encode(latestReleaseURL, forKey: .latestReleaseURL)
    }
}

