//
// OpenAPIProfileEventChangeRemoteImporting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIProfileEventChangeRemoteImporting: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case profileEventChangeRemoteImporting = "ProfileEventChangeRemoteImporting"
    }
    public let type: OpenAPIType = .profileEventChangeRemoteImporting
    public var isImporting: Bool

    public init(isImporting: Bool) {
        self.isImporting = isImporting
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case isImporting
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(isImporting, forKey: .isImporting)
    }
}

