//
// OpenAPIConfigEventRefresh.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIConfigEventRefresh: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case configEventRefresh = "ConfigEventRefresh"
    }
    public let type: OpenAPIType = .configEventRefresh
    public var flags: [OpenAPIConfigFlag]
    public var data: JSON

    public init(flags: [OpenAPIConfigFlag], data: JSON) {
        self.flags = flags
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case flags
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(flags, forKey: .flags)
        try container.encode(data, forKey: .data)
    }
}

