//
// OpenAPIConfigFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIConfigFlag: String, Sendable, Codable, CaseIterable {
    case allowsRelaxedVerification = "allowsRelaxedVerification"
    case appNotWorking = "appNotWorking"
    case forcesRelaxedVerification = "forcesRelaxedVerification"
    case newProfileEncoding = "newProfileEncoding"
    case ovpnV3 = "ovpnV3"
    case unknown = "unknown"
}
