//
// OpenAPIAppUserLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIAppUserLevel: String, Sendable, Codable, CaseIterable {
    case undefined = "undefined"
    case freemium = "freemium"
    case beta = "beta"
    case essentials = "essentials"
    case complete = "complete"
}
