//
// OpenAPIIAPEventNewReceipt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIIAPEventNewReceipt: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case iapeventnewreceipt = "IAPEventNewReceipt"
    }
    public let type: OpenAPIType = .iapeventnewreceipt
    public var originalPurchase: OpenAPIOriginalPurchase?
    public var products: [String]
    public var isBeta: Bool

    public init(originalPurchase: OpenAPIOriginalPurchase? = nil, products: [String], isBeta: Bool) {
        self.originalPurchase = originalPurchase
        self.products = products
        self.isBeta = isBeta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case originalPurchase
        case products
        case isBeta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(originalPurchase, forKey: .originalPurchase)
        try container.encode(products, forKey: .products)
        try container.encode(isBeta, forKey: .isBeta)
    }
}

