//
// OpenAPIAppConstantsLogFormatter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsLogFormatter: Sendable, Codable, Hashable {

    public var timestamp: String
    public var message: String

    public init(timestamp: String, message: String) {
        self.timestamp = timestamp
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(message, forKey: .message)
    }
}

