//
// OpenAPIWebsiteWithPasscode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIWebsiteWithPasscode: Sendable, Codable, Hashable {

    public var url: String
    public var passcode: String?

    public init(url: String, passcode: String? = nil) {
        self.url = url
        self.passcode = passcode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case passcode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(passcode, forKey: .passcode)
    }
}

