//
// OpenAPIIssueAttachment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIIssueAttachment: Sendable, Codable, Hashable {

    public var filename: String
    public var content: Data

    public init(filename: String, content: Data) {
        self.filename = filename
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filename
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filename, forKey: .filename)
        try container.encode(content, forKey: .content)
    }
}

