//
// OpenAPIOriginalPurchase.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIOriginalPurchase: Sendable, Codable, Hashable {

    public var buildNumber: Int
    /** 64-bit millis since UNIX epoch. */
    public var purchaseDate: Int64

    public init(buildNumber: Int, purchaseDate: Int64) {
        self.buildNumber = buildNumber
        self.purchaseDate = purchaseDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case buildNumber
        case purchaseDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(buildNumber, forKey: .buildNumber)
        try container.encode(purchaseDate, forKey: .purchaseDate)
    }
}

