//
// OpenAPIAppConstantsEmailsRecipients.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIAppConstantsEmailsRecipients: Sendable, Codable, Hashable {

    public var issues: String
    public var beta: String

    public init(issues: String, beta: String) {
        self.issues = issues
        self.beta = beta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case issues
        case beta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(issues, forKey: .issues)
        try container.encode(beta, forKey: .beta)
    }
}

