//
// OpenAPIIssue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIIssue: Sendable, Codable, Hashable {

    public var id: UUID
    public var comment: String
    public var appLine: String?
    public var purchasedProducts: [String]
    public var providerLastUpdates: [String: Int64]
    public var appLog: Data?
    public var tunnelLog: Data?
    public var osLine: String
    public var deviceLine: String?

    public init(id: UUID, comment: String, appLine: String? = nil, purchasedProducts: [String], providerLastUpdates: [String: Int64], appLog: Data? = nil, tunnelLog: Data? = nil, osLine: String, deviceLine: String? = nil) {
        self.id = id
        self.comment = comment
        self.appLine = appLine
        self.purchasedProducts = purchasedProducts
        self.providerLastUpdates = providerLastUpdates
        self.appLog = appLog
        self.tunnelLog = tunnelLog
        self.osLine = osLine
        self.deviceLine = deviceLine
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case comment
        case appLine
        case purchasedProducts
        case providerLastUpdates
        case appLog
        case tunnelLog
        case osLine
        case deviceLine
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(comment, forKey: .comment)
        try container.encodeIfPresent(appLine, forKey: .appLine)
        try container.encode(purchasedProducts, forKey: .purchasedProducts)
        try container.encode(providerLastUpdates, forKey: .providerLastUpdates)
        try container.encodeIfPresent(appLog, forKey: .appLog)
        try container.encodeIfPresent(tunnelLog, forKey: .tunnelLog)
        try container.encode(osLine, forKey: .osLine)
        try container.encodeIfPresent(deviceLine, forKey: .deviceLine)
    }
}


extension OpenAPIIssue: Identifiable {}
