//
// OpenAPIAppErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public enum OpenAPIAppErrorCode: String, Sendable, Codable, CaseIterable {
    case binaryFile = "binaryFile"
    case corruptProviderModule = "corruptProviderModule"
    case couldNotLaunch = "couldNotLaunch"
    case emptyProducts = "emptyProducts"
    case emptyProfileName = "emptyProfileName"
    case encoding = "encoding"
    case importError = "importError"
    case incompatibleModules = "incompatibleModules"
    case incompleteModule = "incompleteModule"
    case ineligibleProfile = "ineligibleProfile"
    case interactiveLogin = "interactiveLogin"
    case invalidField = "invalidField"
    case malformedModule = "malformedModule"
    case missingProviderEntity = "missingProviderEntity"
    case moduleRequiresConnection = "moduleRequiresConnection"
    case noActiveModules = "noActiveModules"
    case notFound = "notFound"
    case openVPNPassphraseRequired = "openVPNPassphraseRequired"
    case openVPNUnsupportedCompression = "openVPNUnsupportedCompression"
    case other = "other"
    case partout = "partout"
    case permissionDenied = "permissionDenied"
    case rateLimit = "rateLimit"
    case systemExtension = "systemExtension"
    case timeout = "timeout"
    case unexpectedResponse = "unexpectedResponse"
    case urlRequestFailed = "urlRequestFailed"
    case urlRequestUnavailable = "urlRequestUnavailable"
    case verificationReceiptIsLoading = "verificationReceiptIsLoading"
    case verificationRequiredFeatures = "verificationRequiredFeatures"
    case webReceiver = "webReceiver"
    case webUploader = "webUploader"
    case wireGuardEmptyPeers = "wireGuardEmptyPeers"
}
