//
// OpenAPIConfigBundleConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIConfigBundleConfig: Sendable, Codable, Hashable {

    public var rate: Int
    public var minBuild: Int?
    public var data: JSON?

    public init(rate: Int, minBuild: Int? = nil, data: JSON? = nil) {
        self.rate = rate
        self.minBuild = minBuild
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rate
        case minBuild
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rate, forKey: .rate)
        try container.encodeIfPresent(minBuild, forKey: .minBuild)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

