//
// OpenAPIWebReceiverEventStart.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Partout

public struct OpenAPIWebReceiverEventStart: Sendable, Codable, Hashable {

    public enum OpenAPIType: String, Sendable, Codable, CaseIterable {
        case webReceiverEventStart = "WebReceiverEventStart"
    }
    public let type: OpenAPIType = .webReceiverEventStart
    public var website: OpenAPIWebsiteWithPasscode

    public init(website: OpenAPIWebsiteWithPasscode) {
        self.website = website
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case website
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(website, forKey: .website)
    }
}

