name: 'Prepare build environment'
inputs:
  platform:
    description: 'Platform for match'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - shell: bash
      run: |
        scripts/ci/recognize-match-hostname.sh
        bundle exec fastlane --env ${{ inputs.platform }} preinstall_development_certs
