name: Release

on:
  push:
    branches:
      - "bugfix/public-beta-version"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
  FASTLANE_USERNAME: ${{ secrets.FASTLANE_USERNAME }}
  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  distribute_public_beta:
    name: Distribute Public Beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Fetch build metadata
        run: |
          XCODEPROJ="Passepartout.xcodeproj/project.pbxproj"
          echo "PILOT_APP_VERSION=`ci/version-number.sh $XCODEPROJ`" >> $GITHUB_ENV
          echo "PILOT_BUILD_NUMBER=`ci/build-number.sh $XCODEPROJ`" >> $GITHUB_ENV
      - name: Publish on TestFlight
        env:
          PILOT_GROUPS: ${{ vars.PILOT_GROUPS }}
          PILOT_NOTIFY_EXTERNAL_TESTERS: ${{ vars.PILOT_NOTIFY_EXTERNAL_TESTERS }}
        run: |
          echo "Local version: $PILOT_APP_VERSION"
          echo "Local build: $PILOT_BUILD_NUMBER"
          echo "Env version: ${{ env.PILOT_APP_VERSION }}"
          echo "Env build: ${{ env.PILOT_BUILD_NUMBER }}"
