name: Release

on:
  push:
    tags:
      - "builds/*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
  FASTLANE_USERNAME: ${{ secrets.FASTLANE_USERNAME }}
  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_upload:
    name: Upload to ASC
    runs-on: macos-14
    strategy:
      fail-fast: true
      matrix:
        #platform: ["iOS", "macOS", "tvOS"]
        platform: ["iOS", "macOS"]
    steps:
      - uses: passepartoutvpn/action-access-private-repositories@master
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Upload ${{ matrix.platform }} app
        id: upload_app
        timeout-minutes: 15
        env:
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          PILOT_BETA_APP_FEEDBACK: ${{ secrets.PILOT_BETA_APP_FEEDBACK }}
          PILOT_BETA_APP_REVIEW_INFO: ${{ secrets.PILOT_BETA_APP_REVIEW_INFO }}
          PILOT_GROUPS: ${{ vars.PILOT_GROUPS }}
        run: |
          ci/recognize-match-hostname.sh
          bundle exec fastlane --env ${{ matrix.platform }} beta
