name: Tests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - "master"
      - "hotfix/*"
    paths-ignore:
      - "README.md"
      - ".env.*"
      - "**/*.md"
      - "app-apple/fastlane/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Run checks
    uses: ./.github/workflows/checks.yml
